// Generated from the canonical MKMSZR Memory-and-Allocation-Map.md snapshot.
// Unknown gaps are intentionally not classified as free.
window.MKMSZ_MEMORY_DATA = {
  "snapshot": "2026-09-27",
  "sourceRepo": "smeagol44/MKMSZ-Randomizer",
  "sourceCommit": "f00c1d97cc5b491593790e8fe0544176c63ff26a",
  "sourcePage": "wiki/Memory-and-Allocation-Map.md",
  "rom": {
    "start": 0,
    "end": 16777216,
    "bucketSize": 65536,
    "grid": 16,
    "records": [
      {
        "id": "rom.proof.attack_modern_check_v01_owned_stubs",
        "start": 488912,
        "end": 488924,
        "range": "[0x000775D0, 0x000775DC)",
        "class": "proof-only",
        "owner": "ATTACK combo stub in production GAME SETTINGS tail",
        "scope": "Bounded disposable proof",
        "lifecycle": "Proof artifact only",
        "evidence": "User-reported Runtime-confirmed disposable full-composition check",
        "production_safe": "no",
        "reference": "Memory-and-Allocation-Map.md",
        "notes": "First of three discontiguous intervals of the canonical owned_stubs region; guarded proof edit in an existing production owner."
      },
      {
        "id": "rom.proof.attack_modern_check_v01_owned_stubs.block",
        "start": 489096,
        "end": 489108,
        "range": "[0x00077688, 0x00077694)",
        "class": "proof-only",
        "owner": "ATTACK Block stub in production GAME SETTINGS tail",
        "scope": "Bounded disposable proof",
        "lifecycle": "Proof artifact only",
        "evidence": "User-reported Runtime-confirmed disposable full-composition check",
        "production_safe": "no",
        "reference": "Memory-and-Allocation-Map.md",
        "notes": "Second interval of canonical rom.proof.attack_modern_check_v01_owned_stubs; existing production owner."
      },
      {
        "id": "rom.production.inventory_action_cave",
        "start": 587496,
        "end": 587600,
        "range": "[0x0008F6E8, 0x0008F750)",
        "class": "production",
        "owner": "Four-box action routine",
        "scope": "Global code",
        "lifecycle": "Gameplay",
        "evidence": "Runtime-confirmed behavior; Implementation/CI-confirmed bounds",
        "production_safe": "yes",
        "reference": "inventory_boxes.py; Patch-site registry",
        "notes": "Historical Prison-key callback entered at 0x8F6EC; proof body is not a reusable allocation."
      },
      {
        "id": "rom.production.inventory_helper_cave",
        "start": 632520,
        "end": 632664,
        "range": "[0x0009A6C8, 0x0009A758)",
        "class": "production",
        "owner": "Four-box switch/mask helper composition",
        "scope": "Global code",
        "lifecycle": "Gameplay / transition",
        "evidence": "Runtime-confirmed behavior; Implementation/CI-confirmed 0x90 reservation",
        "production_safe": "yes",
        "reference": "inventory_boxes.py; tests assert SELECTOR_CAVE_SIZE == 0x90",
        "notes": "Toasty visual v06 used [0x9A720,0x9A754) and is rejected for that route; this tail is now production-owned."
      },
      {
        "id": "rom.production.bootstrap_composite",
        "start": 634244,
        "end": 634656,
        "range": "[0x0009AD84, 0x0009AF20)",
        "class": "production",
        "owner": "Native bootstrap + pickup persistence + relocated selector/flow data",
        "scope": "Global code/data",
        "lifecycle": "Stage init / gameplay",
        "evidence": "Runtime-confirmed composition; Implementation/CI-confirmed capacity 0x19C",
        "production_safe": "yes",
        "reference": "native_payload.py, pickup_persistence.py, inventory_boxes.py, flow_bypass.py",
        "notes": "Conflicts with rejected title wrapper at 0x9ADE0 and Sektor v62 proof record [0x9AD90,0x9ADA0). Final four bytes are reserved capacity, not free."
      },
      {
        "id": "rom.proof.attack_modern_check_v01_owned_stubs.capture",
        "start": 634392,
        "end": 634408,
        "range": "[0x0009AE18, 0x0009AE28)",
        "class": "proof-only",
        "owner": "ATTACK retargeted capture stub in production bootstrap",
        "scope": "Bounded disposable proof",
        "lifecycle": "Proof artifact only",
        "evidence": "User-reported Runtime-confirmed disposable full-composition check",
        "production_safe": "no",
        "reference": "Memory-and-Allocation-Map.md",
        "notes": "Third interval of canonical rom.proof.attack_modern_check_v01_owned_stubs; existing production owner."
      },
      {
        "id": "rom.stock.false_zero_cave",
        "start": 660232,
        "end": 660804,
        "range": "[0x000A1308, 0x000A1544)",
        "class": "stock-known",
        "owner": "Stock action/dispatch record area",
        "scope": "Global stock data",
        "lifecycle": "Gameplay/input dispatch",
        "evidence": "Static-confirmed; Runtime-confirmed failure/correction in Sektor v08",
        "production_safe": "no",
        "reference": "Core runtime; MKT compatibility",
        "notes": "Required negative example: zero-filled semantic records were mistaken for a cave; overwriting them caused input-specific hangs."
      },
      {
        "id": "rom.production.shared_file_entry_1a",
        "start": 676168,
        "end": 676180,
        "range": "[0x000A5148, 0x000A5154)",
        "class": "production",
        "owner": "Shared TURN / controls / optional Toasty expansion file-table entry 0x1A",
        "scope": "Global file table",
        "lifecycle": "Stage init",
        "evidence": "TURN production composition Runtime-confirmed; CI guards/bounds",
        "production_safe": "yes",
        "reference": "game_settings_turn.py; toasty.py; Address-and-Patch-Site-Registry.md",
        "notes": "TURN owns the mandatory prefix, modern controls the low extension, and optional CI4 Toasty the high extension. The frontend does not load this file."
      },
      {
        "id": "rom.production.file_entry_1b",
        "start": 676180,
        "end": 676192,
        "range": "[0x000A5154, 0x000A5160)",
        "class": "production",
        "owner": "Global file-table entry 0x1B",
        "scope": "Global file table",
        "lifecycle": "Stage init",
        "evidence": "Runtime-confirmed load/execute; Implementation/CI-confirmed guard",
        "production_safe": "yes",
        "reference": "addresses.py, native_payload.py",
        "notes": "Points to current payload source [0xF10000,0xF10300)."
      },
      {
        "id": "rom.production.file_entry_5e",
        "start": 676984,
        "end": 676996,
        "range": "[0x000A5478, 0x000A5484)",
        "class": "production",
        "owner": "Global file-table entry 0x5E",
        "scope": "Global file table",
        "lifecycle": "Frontend/title",
        "evidence": "Runtime-confirmed title route; Implementation/CI-confirmed guard",
        "production_safe": "yes",
        "reference": "title_branding.py; ROM/overlay/resource map",
        "notes": "Repoints title package to high-ROM allocation."
      },
      {
        "id": "rom.production.key_stage_table",
        "start": 682980,
        "end": 683020,
        "range": "[0x000A6BE4, 0x000A6C0C)",
        "class": "production",
        "owner": "Four-box key-to-stage map",
        "scope": "Global data",
        "lifecycle": "Gameplay / transition",
        "evidence": "Runtime-confirmed masking behavior; Implementation/CI-confirmed 40-byte table",
        "production_safe": "yes",
        "reference": "inventory_boxes.py",
        "notes": "Reuses the obsolete stock default-inventory template after loader replacement."
      },
      {
        "id": "rom.production.live_inventory_initializer",
        "start": 683020,
        "end": 683060,
        "range": "[0x000A6C0C, 0x000A6C34)",
        "class": "production",
        "owner": "Ten-word live-inventory initializer",
        "scope": "Global data",
        "lifecycle": "Run init / inventory",
        "evidence": "Runtime-confirmed four-box system; Implementation/CI-confirmed 40 bytes",
        "production_safe": "yes",
        "reference": "inventory_boxes.py",
        "notes": "Runtime authoritative live window is mapped separately in RDRAM."
      },
      {
        "id": "rom.production.four_box_data",
        "start": 683080,
        "end": 683248,
        "range": "[0x000A6C48, 0x000A6CF0)",
        "class": "production",
        "owner": "Four backing boxes + state + MKBX magic",
        "scope": "Global data",
        "lifecycle": "Run init / gameplay / transition",
        "evidence": "Runtime-confirmed boxes; Implementation/CI-confirmed 0xA8 bytes",
        "production_safe": "yes",
        "reference": "inventory_boxes.py; tests assert exact size",
        "notes": "Gap [0xA6C34,0xA6C48) is deliberately unknown, not absorbed into this owner."
      },
      {
        "id": "rom.stock.xp_cap_table",
        "start": 684028,
        "end": 684048,
        "range": "[0x000A6FFC, 0x000A7010)",
        "class": "stock-known",
        "owner": "Signed XP-cap halfword table",
        "scope": "Global data",
        "lifecycle": "Gameplay",
        "evidence": "Static-confirmed table; current main-stage edits Implementation/CI-confirmed",
        "production_safe": "conditional",
        "reference": "addresses.py, xp_progression.py",
        "notes": "Current production changes only native stage IDs 0,1,2,3,4,5,8,9; the bounded stock table remains protected as a whole."
      },
      {
        "id": "rom.production.boot_branding_text",
        "start": 719256,
        "end": 719396,
        "range": "[0x000AF998, 0x000AFA24)",
        "class": "production",
        "owner": "MKMSZR legal/boot branding strings",
        "scope": "Frontend",
        "lifecycle": "Boot/legal screen",
        "evidence": "Runtime-confirmed",
        "production_safe": "yes",
        "reference": "boot_branding.py exact bounds and guards",
        "notes": "Adjacent to, but distinct from, HUD wrapper allocation."
      },
      {
        "id": "rom.production.box_indicator",
        "start": 719396,
        "end": 719512,
        "range": "[0x000AFA24, 0x000AFA98)",
        "class": "production",
        "owner": "Native BOX n OF 4 wrapper + text",
        "scope": "Global code/data",
        "lifecycle": "Gameplay HUD",
        "evidence": "Runtime-confirmed",
        "production_safe": "yes",
        "reference": "box_indicator.py exact 0x74-byte region",
        "notes": "Entire region is owned even where emitted bytes are zero padding."
      },
      {
        "id": "rom.production.license_text",
        "start": 719512,
        "end": 719548,
        "range": "[0x000AFA98, 0x000AFABC)",
        "class": "production",
        "owner": "MKMSZR license line",
        "scope": "Frontend",
        "lifecycle": "Boot/legal screen",
        "evidence": "Runtime-confirmed",
        "production_safe": "yes",
        "reference": "boot_branding.py exact bounds and guard",
        "notes": "Do not merge trailing bytes outside 0xAFABC without evidence."
      },
      {
        "id": "rom.stock.stage_resource.bridge",
        "start": 2711872,
        "end": 2729072,
        "range": "[0x00296140, 0x0029A470)",
        "class": "stock-known",
        "owner": "Bridge stage resource file",
        "scope": "Stage 8 resource",
        "lifecycle": "Bridge load/gameplay",
        "evidence": "Static-confirmed; runtime base matched",
        "production_safe": "no",
        "reference": "ROM/overlay/resource map",
        "notes": "Resource ownership does not make unused-looking selector/data bytes free."
      },
      {
        "id": "rom.stock.stage_resource.fire",
        "start": 3703392,
        "end": 3712912,
        "range": "[0x00388260, 0x0038A790)",
        "class": "stock-known",
        "owner": "Fire stage resource file",
        "scope": "Stage 5 resource",
        "lifecycle": "Fire load/gameplay",
        "evidence": "Static-confirmed; runtime base matched",
        "production_safe": "no",
        "reference": "ROM/overlay/resource map",
        "notes": "A separate disposable proof relocation exists below."
      },
      {
        "id": "rom.stock.stage_resource.fortress",
        "start": 3905280,
        "end": 3919136,
        "range": "[0x003B9700, 0x003BCD20)",
        "class": "stock-known",
        "owner": "Fortress stage resource file",
        "scope": "Stage 9 resource",
        "lifecycle": "Fortress load/gameplay",
        "evidence": "Static-confirmed; runtime base matched",
        "production_safe": "no",
        "reference": "ROM/overlay/resource map",
        "notes": "No gap/capacity inference is made."
      },
      {
        "id": "rom.stock.stage_resource.prison",
        "start": 4310656,
        "end": 4329328,
        "range": "[0x0041C680, 0x00420F70)",
        "class": "stock-known",
        "owner": "Prison stage resource file",
        "scope": "Stage 4 resource",
        "lifecycle": "Prison load/gameplay",
        "evidence": "Static-confirmed; runtime base matched",
        "production_safe": "no",
        "reference": "ROM/overlay/resource map",
        "notes": "Extension-selector proofs relocate/expand a copy; stock bytes remain protected."
      },
      {
        "id": "rom.stock.file_5e_title",
        "start": 5124192,
        "end": 5317696,
        "range": "[0x004E3060, 0x00512440)",
        "class": "stock-known",
        "owner": "Stock compressed title package, file 0x5E",
        "scope": "Frontend/title resource",
        "lifecycle": "Title load",
        "evidence": "Static-confirmed",
        "production_safe": "no",
        "reference": "title_branding.py; ROM/overlay/resource map",
        "notes": "Current production retains this stock source but repoints the live file entry to high ROM. Retained bytes are not declared free."
      },
      {
        "id": "rom.stock.stage_resource.temple",
        "start": 5322512,
        "end": 5387120,
        "range": "[0x00513710, 0x00523370)",
        "class": "stock-known",
        "owner": "Temple stage resource file",
        "scope": "Stage 0 resource",
        "lifecycle": "Temple load/gameplay",
        "evidence": "Static-confirmed; runtime base matched",
        "production_safe": "no",
        "reference": "ROM/overlay/resource map",
        "notes": "No gap/capacity inference is made."
      },
      {
        "id": "rom.stock.stage_resource.water",
        "start": 6363008,
        "end": 6388832,
        "range": "[0x00611780, 0x00617C60)",
        "class": "stock-known",
        "owner": "Water stage resource file",
        "scope": "Stage 2 resource",
        "lifecycle": "Water load/gameplay",
        "evidence": "Static-confirmed; runtime base matched",
        "production_safe": "no",
        "reference": "ROM/overlay/resource map",
        "notes": "No gap/capacity inference is made."
      },
      {
        "id": "rom.stock.stage_resource.wind",
        "start": 6915712,
        "end": 6924320,
        "range": "[0x00698680, 0x0069A820)",
        "class": "stock-known",
        "owner": "Wind stage resource file",
        "scope": "Stage 1 resource",
        "lifecycle": "Wind load/gameplay",
        "evidence": "Static-confirmed; runtime base matched",
        "production_safe": "no",
        "reference": "ROM/overlay/resource map",
        "notes": "No gap/capacity inference is made."
      },
      {
        "id": "rom.stock.stage_resource.earth",
        "start": 7057088,
        "end": 7197808,
        "range": "[0x006BAEC0, 0x006DD470)",
        "class": "stock-known",
        "owner": "Earth stage resource file",
        "scope": "Stage 3 resource",
        "lifecycle": "Earth load/gameplay",
        "evidence": "Static-confirmed; runtime base matched",
        "production_safe": "no",
        "reference": "ROM/overlay/resource map",
        "notes": "No gap/capacity inference is made."
      },
      {
        "id": "rom.stock.file_87_subzero",
        "start": 7637280,
        "end": 7922432,
        "range": "[0x00748920, 0x0078E300)",
        "class": "stock-known",
        "owner": "Stock Sub-Zero fighter resource, file 0x87",
        "scope": "Global fighter resource",
        "lifecycle": "Gameplay",
        "evidence": "Static-confirmed; repeatedly used as donor-proof baseline",
        "production_safe": "no",
        "reference": "Sektor mapping",
        "notes": "Optional outfit recolor edits a guarded palette subset inside this owned file; that does not make other bytes free."
      },
      {
        "id": "rom.proof.fire_resource_relocation",
        "start": 15728640,
        "end": 15739880,
        "range": "[0x00F00000, 0x00F02BE8)",
        "class": "proof-only",
        "owner": "Foreign Prison-key-in-Fire resource proof",
        "scope": "Disposable proof",
        "lifecycle": "Artifact-specific",
        "evidence": "Runtime-confirmed bounded proof",
        "production_safe": "no",
        "reference": "Memory-and-Allocation-Map.md",
        "notes": "Architecture evidence only. The location is not a production allocation promise."
      },
      {
        "id": "rom.production.payload_source",
        "start": 15794176,
        "end": 15795120,
        "range": "[0x00F10000, 0x00F103B0)",
        "class": "production",
        "owner": "MKMSZR Runtime V2 reloadable code payload",
        "scope": "Generated ROM output",
        "lifecycle": "Stage init reload; runtime code",
        "evidence": "Runtime-confirmed through the rainbow full-composition proof; Implementation/CI-confirmed exactly 0x3B0 bytes",
        "production_safe": "yes",
        "reference": "native_payload.py, runtime_v2.py, xp_progression.py, rainbow_palette.py",
        "notes": "File 0x1B points here. Source bytes being FF in the clean ROM are only a guard, not the reason this ownership is accepted."
      },
      {
        "id": "rom.production.rainbow_file_87",
        "start": 15859712,
        "end": 16153056,
        "range": "[0x00F20000, 0x00F679E0)",
        "class": "production",
        "owner": "Optional rainbow outfit relocated Sub-Zero file 0x87 plus 64-palette bank",
        "scope": "Generated ROM output",
        "lifecycle": "Rainbow gameplay only",
        "evidence": "Runtime-confirmed; production output for seed RAINBOW64 is byte-identical to proof v01",
        "production_safe": "conditional",
        "reference": "rainbow_palette.py; guarded stock file entry and destination FF capacity",
        "notes": "Owned only when outfit mode is rainbow; stock file body is copied intact before the appended 0x2000-byte palette bank."
      },
      {
        "id": "rom.proof.sektor_v62_file_87",
        "start": 15990784,
        "end": 16311292,
        "range": "[0x00F40000, 0x00F8E3FC)",
        "class": "proof-only",
        "owner": "Sektor v62 relocated fighter file 0x87",
        "scope": "Disposable proof",
        "lifecycle": "Artifact-specific",
        "evidence": "Runtime-confirmed bounded combo route",
        "production_safe": "no",
        "reference": "Memory-and-Allocation-Map.md",
        "notes": "Does not overlap current title allocation, but larger historical Sektor proof footprints crossed into the later title-owned high-ROM area; proof-history bounds remain artifact-specific."
      },
      {
        "id": "rom.proof.sektor_v70_file_87",
        "start": 15990784,
        "end": 16312208,
        "range": "[0x00F40000, 0x00F8E790)",
        "class": "proof-only",
        "owner": "Sektor v70 chest + straight-missile fighter file 0x87",
        "scope": "Bounded disposable proof",
        "lifecycle": "Proof artifact only",
        "evidence": "Partially Runtime-confirmed missile presentation/flight route",
        "production_safe": "no",
        "reference": "Memory-and-Allocation-Map.md",
        "notes": "0x4E790 bytes; Fortress/Prison allocation safety was not revalidated; no new safe envelope."
      },
      {
        "id": "rom.proof.sektor_v75_file_87",
        "start": 15990784,
        "end": 16312208,
        "range": "[0x00F40000, 0x00F8E790)",
        "class": "proof-only",
        "owner": "Sektor v75 relocated fighter file 0x87",
        "scope": "Bounded disposable proof",
        "lifecycle": "Proof artifact only",
        "evidence": "Runtime-confirmed bounded missile-flight route",
        "production_safe": "no",
        "reference": "Memory-and-Allocation-Map.md",
        "notes": "Uses proof helper [0x9ADA0,0x9AF20) inside current production bootstrap ownership; cannot combine as-is."
      },
      {
        "id": "rom.production.turn_shared_prefix",
        "start": 16154624,
        "end": 16155652,
        "range": "[0x00F68000, 0x00F68404)",
        "class": "production",
        "owner": "TURN native control module / shared file-0x1A prefix",
        "scope": "Global high ROM",
        "lifecycle": "Stage init / gameplay",
        "evidence": "Runtime-confirmed production composition; CI-confirmed 0x404-byte module",
        "production_safe": "yes",
        "reference": "game_settings_turn.py; tests/test_game_settings_turn.py",
        "notes": "Mandatory prefix of shared file 0x1A. The frontend menu wrapper is global/title-resident; this gameplay module is loaded only at stage init."
      },
      {
        "id": "rom.production.controls_extension",
        "start": 16155664,
        "end": 16158816,
        "range": "[0x00F68410, 0x00F69060)",
        "class": "production",
        "owner": "Guarded modern ATTACK / SPECIALS / JUMP / RUN helpers",
        "scope": "Global high ROM",
        "lifecycle": "Stage init / gameplay",
        "evidence": "Runtime-confirmed in accepted v02 composition; builder byte parity confirmed",
        "production_safe": "yes",
        "reference": "controls_production.py; Memory-and-Allocation-Map.md",
        "notes": "Low extension of shared file 0x1A; runtime [0x801AFC30,0x801B0880). ROM alignment gaps remain inside the shared file."
      },
      {
        "id": "rom.proof.attack_modern_check_v01_low_extension",
        "start": 16155652,
        "end": 16156160,
        "range": "[0x00F68404, 0x00F68600)",
        "class": "proof-only",
        "owner": "ATTACK disposable full-composition helper after TURN prefix",
        "scope": "Bounded disposable proof",
        "lifecycle": "Proof artifact only",
        "evidence": "User-reported Runtime-confirmed; builder guards/bounds statically checked",
        "production_safe": "no",
        "reference": "Memory-and-Allocation-Map.md",
        "notes": "Loaded at [0x801AFC24,0x801AFE20); bounded before Toasty source and runtime; not generally free."
      },
      {
        "id": "rom.production.toasty_module",
        "start": 16160736,
        "end": 16168400,
        "range": "[0x00F697E0, 0x00F6B5D0)",
        "class": "production",
        "owner": "Packed Toasty code, 16-entry TLUT, tables, state, and CI4 slices",
        "scope": "Generated ROM output",
        "lifecycle": "Stage init / gameplay when optional donor is supplied",
        "evidence": "Runtime-confirmed in accepted controls + CI4 Toasty v02 production composition",
        "production_safe": "conditional",
        "reference": "toasty.py; toasty_codegen.py",
        "notes": "Optional module begins at the ROM offset corresponding to runtime 0x801B1000 inside shared file 0x1A."
      },
      {
        "id": "rom.production.toasty_audio_sample",
        "start": 16168400,
        "end": 16170470,
        "range": "[0x00F6B5D0, 0x00F6BDE6)",
        "class": "production",
        "owner": "Donor-backed encoded audio sample",
        "scope": "Generated ROM output",
        "lifecycle": "Gameplay audio when optional donor is supplied",
        "evidence": "Runtime-confirmed in TURN + donor-backed production composition",
        "production_safe": "conditional",
        "reference": "toasty.py; Toasty-Audio-Research.md",
        "notes": "Donor bytes are extracted locally from the user's supported MKT ROM and are not stored in the repository."
      },
      {
        "id": "rom.proof.control_facing_v02_module",
        "start": 16195584,
        "end": 16196200,
        "range": "[0x00F72000, 0x00F72268)",
        "class": "proof-only",
        "owner": "Direction-facing v02 expansion module for file 0x1A",
        "scope": "Bounded disposable proof",
        "lifecycle": "Proof artifact only",
        "evidence": "Runtime-confirmed bounded control route",
        "production_safe": "no",
        "reference": "Memory-and-Allocation-Map.md",
        "notes": "Proof-only clean-ROM source; not a free-space declaration."
      },
      {
        "id": "rom.proof.toasty_v43_feature",
        "start": 16199680,
        "end": 16201600,
        "range": "[0x00F73000, 0x00F73780)",
        "class": "proof-only",
        "owner": "Toasty v43 compact feature file 0x12",
        "scope": "Bounded disposable proof",
        "lifecycle": "Proof artifact only",
        "evidence": "Implementation/static-confirmed; runtime Pending",
        "production_safe": "no",
        "reference": "Memory-and-Allocation-Map.md",
        "notes": "Loads into production-reserved expansion pool; artifact-specific proof, not production allocation."
      },
      {
        "id": "rom.production.title_high",
        "start": 16318464,
        "end": 16519168,
        "range": "[0x00F90000, 0x00FC1000)",
        "class": "production",
        "owner": "Generated compressed title file 0x5E",
        "scope": "Generated ROM output",
        "lifecycle": "Frontend/title",
        "evidence": "Runtime-confirmed full production composition",
        "production_safe": "yes",
        "reference": "title_branding.py capacity 0x31000",
        "notes": "Actual compressed end is build-dependent (SUB-ZERO: 0xFC017F; SEKTOR: 0xFC014F). Remaining capacity stays reserved, not free."
      }
    ]
  },
  "rdram": {
    "start": 0,
    "end": 4194304,
    "bucketSize": 16384,
    "grid": 16,
    "records": [
      {
        "id": "rdram.production.inventory_action_cave",
        "start": 584424,
        "end": 584528,
        "range": "[0x08EAE8, 0x08EB50)",
        "aliases": "KSEG0 [0x8008EAE8,0x8008EB50); KSEG1 [0xA008EAE8,0xA008EB50)",
        "class": "production",
        "owner": "Four-box action routine",
        "scope": "Global code",
        "lifecycle": "Gameplay",
        "evidence": "Runtime-confirmed behavior; CI-confirmed bounds",
        "production_safe": "yes",
        "reference": "inventory_boxes.py",
        "notes": "Same physical bytes as the displayed aliases; count once."
      },
      {
        "id": "rdram.production.inventory_helper_cave",
        "start": 629448,
        "end": 629592,
        "range": "[0x099AC8, 0x099B58)",
        "aliases": "KSEG0 [0x80099AC8,0x80099B58); KSEG1 [0xA0099AC8,0xA0099B58)",
        "class": "production",
        "owner": "Four-box helper composition",
        "scope": "Global code",
        "lifecycle": "Gameplay / transition",
        "evidence": "Runtime-confirmed behavior; CI-confirmed bounds",
        "production_safe": "yes",
        "reference": "inventory_boxes.py",
        "notes": "Historical proof tail use is not reusable."
      },
      {
        "id": "rdram.production.bootstrap_composite",
        "start": 631172,
        "end": 631584,
        "range": "[0x09A184, 0x09A320)",
        "aliases": "KSEG0 [0x8009A184,0x8009A320); KSEG1 [0xA009A184,0xA009A320)",
        "class": "production",
        "owner": "Bootstrap/persistence/selector composite",
        "scope": "Global code/data",
        "lifecycle": "Stage init / gameplay",
        "evidence": "Runtime-confirmed composition; CI-confirmed 0x19C capacity",
        "production_safe": "yes",
        "reference": "native_payload.py, pickup_persistence.py, inventory_boxes.py",
        "notes": "Mirrors the current global-code ROM owner rom.production.bootstrap_composite; this is not a ROM=VA assumption but an established segment mapping."
      },
      {
        "id": "rdram.stock.false_zero_cave",
        "start": 657160,
        "end": 657732,
        "range": "[0x0A0708, 0x0A0944)",
        "aliases": "KSEG0 [0x800A0708,0x800A0944); KSEG1 [0xA00A0708,0xA00A0944)",
        "class": "stock-known",
        "owner": "Stock action/dispatch data",
        "scope": "Global data",
        "lifecycle": "Gameplay/input dispatch",
        "evidence": "Static-confirmed; Runtime-confirmed negative control",
        "production_safe": "no",
        "reference": "MKT compatibility",
        "notes": "Zero-filled records are semantic live data, not padding."
      },
      {
        "id": "rdram.production.file_entry_1b",
        "start": 673108,
        "end": 673120,
        "range": "[0x0A4554, 0x0A4560)",
        "aliases": "KSEG0 [0x800A4554,0x800A4560); KSEG1 [0xA00A4554,0xA00A4560)",
        "class": "production",
        "owner": "Runtime global file-table entry 0x1B",
        "scope": "Global data",
        "lifecycle": "Stage init",
        "evidence": "Runtime-confirmed loader path",
        "production_safe": "yes",
        "reference": "Global table base 0x800A4410, 12-byte entries",
        "notes": "Alias of one physical table entry, not a separate allocation."
      },
      {
        "id": "rdram.production.file_entry_5e",
        "start": 673912,
        "end": 673924,
        "range": "[0x0A4878, 0x0A4884)",
        "aliases": "KSEG0 [0x800A4878,0x800A4884); KSEG1 [0xA00A4878,0xA00A4884)",
        "class": "production",
        "owner": "Runtime global file-table entry 0x5E",
        "scope": "Global data",
        "lifecycle": "Frontend/title load",
        "evidence": "Runtime-confirmed title route",
        "production_safe": "yes",
        "reference": "Global table base 0x800A4410, 12-byte entries",
        "notes": "Runtime table reflects the patched file descriptor."
      },
      {
        "id": "rdram.production.key_stage_table",
        "start": 679908,
        "end": 679948,
        "range": "[0x0A5FE4, 0x0A600C)",
        "aliases": "KSEG0 [0x800A5FE4,0x800A600C); KSEG1 [0xA00A5FE4,0xA00A600C)",
        "class": "production",
        "owner": "Key-to-stage map",
        "scope": "Global data",
        "lifecycle": "Gameplay / transition",
        "evidence": "Runtime-confirmed masking; CI-confirmed 40 bytes",
        "production_safe": "yes",
        "reference": "inventory_boxes.py",
        "notes": "Directly precedes live inventory but is a separate owner."
      },
      {
        "id": "rdram.production.live_inventory",
        "start": 679948,
        "end": 679988,
        "range": "[0x0A600C, 0x0A6034)",
        "aliases": "KSEG0 [0x800A600C,0x800A6034); KSEG1 [0xA00A600C,0xA00A6034)",
        "class": "production",
        "owner": "Native ten-slot live inventory window",
        "scope": "Global mutable data",
        "lifecycle": "Gameplay / inventory",
        "evidence": "Runtime-confirmed",
        "production_safe": "yes",
        "reference": "inventory_boxes.py; Persistence/inventory",
        "notes": "Live window is not authoritative across box switching; backing boxes are."
      },
      {
        "id": "rdram.production.four_boxes",
        "start": 680008,
        "end": 680168,
        "range": "[0x0A6048, 0x0A60E8)",
        "aliases": "KSEG0 [0x800A6048,0x800A60E8); KSEG1 [0xA00A6048,0xA00A60E8)",
        "class": "production",
        "owner": "Four authoritative ten-word backing boxes",
        "scope": "Global mutable data",
        "lifecycle": "Run gameplay / transitions",
        "evidence": "Runtime-confirmed",
        "production_safe": "yes",
        "reference": "inventory_boxes.py",
        "notes": "Gap [0x0A6034,0x0A6048) remains unknown."
      },
      {
        "id": "rdram.production.box_state",
        "start": 680168,
        "end": 680172,
        "range": "[0x0A60E8, 0x0A60EC)",
        "aliases": "KSEG0 0x800A60E8; KSEG1 0xA00A60E8",
        "class": "production",
        "owner": "Active-box index/latch word",
        "scope": "Global mutable data",
        "lifecycle": "Run gameplay",
        "evidence": "Runtime-confirmed",
        "production_safe": "yes",
        "reference": "inventory_boxes.py",
        "notes": "Bits 0..1 active index; latch includes 0x100."
      },
      {
        "id": "rdram.production.box_magic",
        "start": 680172,
        "end": 680176,
        "range": "[0x0A60EC, 0x0A60F0)",
        "aliases": "KSEG0 0x800A60EC; KSEG1 0xA00A60EC",
        "class": "production",
        "owner": "MKBX magic",
        "scope": "Global mutable data",
        "lifecycle": "Run initialization / reconstruction",
        "evidence": "Implementation/CI-confirmed; exercised by runtime system",
        "production_safe": "yes",
        "reference": "inventory_boxes.py",
        "notes": "Magic 0x4D4B4258."
      },
      {
        "id": "rdram.stock.xp_cap_table",
        "start": 680956,
        "end": 680976,
        "range": "[0x0A63FC, 0x0A6410)",
        "aliases": "KSEG0 [0x800A63FC,0x800A6410); KSEG1 [0xA00A63FC,0xA00A6410)",
        "class": "stock-known",
        "owner": "Signed XP-cap table with production main-stage edits",
        "scope": "Global data",
        "lifecycle": "Gameplay",
        "evidence": "Static-confirmed; production writes Implementation/CI-confirmed",
        "production_safe": "conditional",
        "reference": "addresses.py, xp_progression.py",
        "notes": "Only selected halfwords are production-edited."
      },
      {
        "id": "rdram.production.boot_branding_text",
        "start": 716184,
        "end": 716324,
        "range": "[0x0AED98, 0x0AEE24)",
        "aliases": "KSEG0 [0x800AED98,0x800AEE24); KSEG1 [0xA00AED98,0xA00AEE24)",
        "class": "production",
        "owner": "MKMSZR legal/boot strings",
        "scope": "Global data",
        "lifecycle": "Boot/legal screen",
        "evidence": "Runtime-confirmed",
        "production_safe": "yes",
        "reference": "boot_branding.py pointer targets",
        "notes": "Established global-segment mapping; count physical bytes once."
      },
      {
        "id": "rdram.production.box_indicator",
        "start": 716324,
        "end": 716440,
        "range": "[0x0AEE24, 0x0AEE98)",
        "aliases": "KSEG0 [0x800AEE24,0x800AEE98); KSEG1 [0xA00AEE24,0xA00AEE98)",
        "class": "production",
        "owner": "Native box HUD wrapper/text",
        "scope": "Global code/data",
        "lifecycle": "Gameplay HUD",
        "evidence": "Runtime-confirmed",
        "production_safe": "yes",
        "reference": "box_indicator.py",
        "notes": "Exact region mirrors ROM owner."
      },
      {
        "id": "rdram.production.license_text",
        "start": 716440,
        "end": 716476,
        "range": "[0x0AEE98, 0x0AEEBC)",
        "aliases": "KSEG0 [0x800AEE98,0x800AEEBC); KSEG1 [0xA00AEE98,0xA00AEEBC)",
        "class": "production",
        "owner": "MKMSZR license string",
        "scope": "Global data",
        "lifecycle": "Boot/legal screen",
        "evidence": "Runtime-confirmed",
        "production_safe": "yes",
        "reference": "boot_branding.py",
        "notes": "Exact bounded string storage."
      },
      {
        "id": "rdram.stock.current_xp",
        "start": 1122316,
        "end": 1122320,
        "range": "[0x11200C, 0x112010)",
        "aliases": "KSEG0 0x8011200C; KSEG1 0xA011200C",
        "class": "stock-known",
        "owner": "Native current-XP word used by production progression",
        "scope": "Global mutable data",
        "lifecycle": "Gameplay / stage transition",
        "evidence": "Static-confirmed and Runtime-confirmed on progression routes",
        "production_safe": "conditional",
        "reference": "addresses.py; XP/progression",
        "notes": "Production owns behavior around the stock variable, not surrounding words."
      },
      {
        "id": "rdram.production.runtime_core",
        "start": 1766432,
        "end": 1766900,
        "range": "[0x1AF420, 0x1AF5F4)",
        "aliases": "KSEG0 [0x801AF420,0x801AF5F4); KSEG1 [0xA01AF420,0xA01AF5F4)",
        "class": "production",
        "owner": "Runtime V2 init + pickup-persistence code through actual +0x1D4 core end",
        "scope": "Reserved MKMSZR block",
        "lifecycle": "Reloaded at stage init; executes during init/gameplay hooks",
        "evidence": "Runtime-confirmed; exact emitted size CI-confirmed",
        "production_safe": "yes",
        "reference": "runtime_v2.py, pickup_persistence.py; actual persistence core size 0x1D4",
        "notes": "Subrange of the 1 KiB reservation."
      },
      {
        "id": "rdram.production.inventory_payload",
        "start": 1766900,
        "end": 1766944,
        "range": "[0x1AF5F4, 0x1AF620)",
        "aliases": "KSEG0 [0x801AF5F4,0x801AF620); KSEG1 [0xA01AF5F4,0xA01AF620)",
        "class": "production",
        "owner": "Four-box filtered-save helper",
        "scope": "Reserved MKMSZR block",
        "lifecycle": "Gameplay / transition",
        "evidence": "Runtime-confirmed composition; CI-confirmed bounds",
        "production_safe": "yes",
        "reference": "inventory_boxes.py payload +0x1D4..+0x200",
        "notes": "Reuses the production payload tail intentionally."
      },
      {
        "id": "rdram.production.xp_payload",
        "start": 1766944,
        "end": 1767168,
        "range": "[0x1AF620, 0x1AF700)",
        "aliases": "KSEG0 [0x801AF620,0x801AF700); KSEG1 [0xA01AF620,0xA01AF700)",
        "class": "production",
        "owner": "XP progression callback, threshold table, restore helper, and bounded padding",
        "scope": "Reserved MKMSZR block",
        "lifecycle": "Pickup / stage transition",
        "evidence": "Runtime-confirmed Diagnostic B behavior; CI-confirmed meaningful content stays below +0x2E0",
        "production_safe": "yes",
        "reference": "xp_progression.py",
        "notes": "The formerly zero [+0x2E0,+0x300) tail is intentionally released to the optional runtime-feature region below."
      },
      {
        "id": "rdram.production.optional_runtime_tail",
        "start": 1767168,
        "end": 1767376,
        "range": "[0x1AF700, 0x1AF7D0)",
        "aliases": "KSEG0 [0x801AF700,0x801AF7D0); KSEG1 [0xA01AF700,0xA01AF7D0)",
        "class": "production",
        "owner": "Optional Runtime V2 feature code tail",
        "scope": "Reserved MKMSZR block",
        "lifecycle": "Gameplay",
        "evidence": "Runtime-confirmed by rainbow v01; CI-confirmed bounds",
        "production_safe": "yes",
        "reference": "runtime_v2.py, rainbow_palette.py",
        "notes": "Rainbow owns [0x1AF700,0x1AF7CC) with its 0xCC-byte helper; [0x1AF7CC,0x1AF7D0) remains reserved. In non-rainbow builds the whole interval remains reserved/zero."
      },
      {
        "id": "rdram.production.state_header",
        "start": 1767376,
        "end": 1767408,
        "range": "[0x1AF7D0, 0x1AF7F0)",
        "aliases": "KSEG0 [0x801AF7D0,0x801AF7F0); KSEG1 [0xA01AF7D0,0xA01AF7F0)",
        "class": "production",
        "owner": "MKSV V2 state header",
        "scope": "Persistent MKMSZR state",
        "lifecycle": "Survives payload reload / normal stage lifecycle",
        "evidence": "Runtime-confirmed through rainbow full composition; CI-confirmed layout",
        "production_safe": "yes",
        "reference": "runtime_v2.py header size 0x20",
        "notes": "Header validates magic/version/size/header-size; total state size is 0x50."
      },
      {
        "id": "rdram.production.pickup_state",
        "start": 1767408,
        "end": 1767440,
        "range": "[0x1AF7F0, 0x1AF810)",
        "aliases": "KSEG0 [0x801AF7F0,0x801AF810); KSEG1 [0xA01AF7F0,0xA01AF810)",
        "class": "production",
        "owner": "Eight stage ordinary-pickup bitset words",
        "scope": "Persistent MKMSZR state",
        "lifecycle": "Run lifecycle until reset boundary",
        "evidence": "Runtime-confirmed representative persistence in all eight stages and in the rainbow full composition",
        "production_safe": "yes",
        "reference": "pickup_persistence.py descriptors use state offsets +0x20..+0x3C",
        "notes": "Scripted/special mechanisms are outside these bitsets."
      },
      {
        "id": "rdram.production.xp_state",
        "start": 1767440,
        "end": 1767448,
        "range": "[0x1AF810, 0x1AF818)",
        "aliases": "KSEG0 [0x801AF810,0x801AF818); KSEG1 [0xA01AF810,0xA01AF818)",
        "class": "production",
        "owner": "Progression acquired-count + persistent-XP words",
        "scope": "Persistent MKMSZR state",
        "lifecycle": "Run lifecycle / stage transition",
        "evidence": "Runtime-confirmed on bounded Diagnostic B routes and rainbow full composition",
        "production_safe": "yes",
        "reference": "xp_progression.py state +0x40/+0x44",
        "notes": "Full nine-tier run remains a validation limit, not an allocation ambiguity."
      },
      {
        "id": "rdram.production.rainbow_phase",
        "start": 1767448,
        "end": 1767452,
        "range": "[0x1AF818, 0x1AF81C)",
        "aliases": "KSEG0 0x801AF818; KSEG1 0xA01AF818",
        "class": "production",
        "owner": "Optional rainbow phase word",
        "scope": "Persistent MKMSZR state",
        "lifecycle": "Rainbow gameplay",
        "evidence": "Runtime-confirmed in full-composition v01",
        "production_safe": "conditional",
        "reference": "rainbow_palette.py state offset +0x48",
        "notes": "Used only in rainbow mode; initialized by the common V2 state initializer."
      },
      {
        "id": "rdram.production.state_reserved_tail",
        "start": 1767452,
        "end": 1767456,
        "range": "[0x1AF81C, 0x1AF820)",
        "aliases": "KSEG0 [0x801AF81C,0x801AF820); KSEG1 [0xA01AF81C,0xA01AF820)",
        "class": "production",
        "owner": "Runtime V2 reserved final word; transient TURN editor halfword use",
        "scope": "Reserved MKMSZR state",
        "lifecycle": "Frontend editor / run lifecycle",
        "evidence": "Runtime-confirmed production composition for transient editor use; CI-confirmed reservation boundary",
        "production_safe": "yes",
        "reference": "runtime_v2.py; game_settings_turn.py",
        "notes": "GAME SETTINGS uses KSEG1 0xA01AF81C transiently while open. Durable TURN ownership is 0x800A60E8 bit 0x0200. Not free."
      },
      {
        "id": "rdram.production.expansion_pool",
        "start": 1767456,
        "end": 1782816,
        "range": "[0x1AF820, 0x1B3420)",
        "aliases": "KSEG0 [0x801AF820,0x801B3420); KSEG1 [0xA01AF820,0xA01B3420)",
        "class": "production",
        "owner": "MKMSZR 15 KiB expansion-pool reservation",
        "scope": "Reserved MKMSZR block",
        "lifecycle": "Global reservation; feature slices assigned at build time",
        "evidence": "16 KiB arena-floor proof Runtime-confirmed across all eight safe stages; allocator/bounds CI-confirmed",
        "production_safe": "yes",
        "reference": "allocations.py; tests/test_expansion_allocations.py",
        "notes": "Parent reservation, not free space. TURN and modern controls own mandatory low suballocations; optional CI4 Toasty owns the high suballocation when present."
      },
      {
        "id": "rdram.production.turn_module",
        "start": 1767456,
        "end": 1768484,
        "range": "[0x1AF820, 0x1AFC24)",
        "aliases": "KSEG0 [0x801AF820,0x801AFC24); KSEG1 [0xA01AF820,0xA01AFC24)",
        "class": "production",
        "owner": "TURN v10/v06 native control module",
        "scope": "Expansion-pool suballocation",
        "lifecycle": "Stage init / gameplay",
        "evidence": "Runtime-confirmed production composition; CI-confirmed 0x404-byte allocation",
        "production_safe": "yes",
        "reference": "game_settings_turn.py; tests/test_game_settings_turn.py",
        "notes": "Loaded only at stage init through shared file 0x1A; never loaded from the frontend."
      },
      {
        "id": "rdram.production.controls_extension",
        "start": 1768496,
        "end": 1771648,
        "range": "[0x1AFC30, 0x1B0880)",
        "aliases": "KSEG0 [0x801AFC30,0x801B0880); KSEG1 [0xA01AFC30,0xA01B0880)",
        "class": "production",
        "owner": "Modern ATTACK / SPECIALS / JUMP / RUN helpers and state",
        "scope": "Expansion-pool suballocation",
        "lifecycle": "Stage init / gameplay",
        "evidence": "Accepted v02 Runtime-confirmed; shared-builder byte parity",
        "production_safe": "yes",
        "reference": "controls_production.py; Memory-and-Allocation-Map.md",
        "notes": "Ends 0x780 bytes before optional CI4 Toasty at 0x801B1000."
      },
      {
        "id": "rdram.production.toasty_module",
        "start": 1773568,
        "end": 1781232,
        "range": "[0x1B1000, 0x1B2DF0)",
        "aliases": "KSEG0 [0x801B1000,0x801B2DF0); KSEG1 [0xA01B1000,0xA01B2DF0)",
        "class": "production",
        "owner": "Conditional CI4 Toasty packed native module",
        "scope": "MKMSZR expansion pool",
        "lifecycle": "Stage init / gameplay when optional donor is supplied",
        "evidence": "v02 Runtime-confirmed controls / CI4 composition; builder byte parity",
        "production_safe": "conditional",
        "reference": "toasty_codegen.py; tests/test_toasty.py",
        "notes": "Uses 0x1DF0 bytes at the 0x801B1000-aligned high slice and leaves 0x630 bytes before the reserved-pool boundary."
      },
      {
        "id": "rdram.proof.toasty_v43_feature",
        "start": 1767456,
        "end": 1769376,
        "range": "[0x1AF820, 0x1AFFA0)",
        "aliases": "KSEG0 [0x801AF820,0x801AFFA0); KSEG1 [0xA01AF820,0xA01AFFA0)",
        "class": "proof-only",
        "owner": "Toasty v43 loaded feature slice",
        "scope": "Disposable proof",
        "lifecycle": "Stage init / gameplay",
        "evidence": "v42 presentation runtime-confirmed; v43 trigger wrapper static-confirmed",
        "production_safe": "no",
        "reference": "Toasty-Visual-Research.md",
        "notes": "Historical proof suballocation inside the now-production expansion pool. It does not establish reusable space."
      },
      {
        "id": "rdram.stock.pickup_context_pointer",
        "start": 3067424,
        "end": 3067428,
        "range": "[0x2ECE20, 0x2ECE24)",
        "aliases": "KSEG0 0x802ECE20; KSEG1 0xA02ECE20",
        "class": "stock-known",
        "owner": "Live pickup-manager process/context pointer slot",
        "scope": "Stage runtime",
        "lifecycle": "Stage manager construction/gameplay",
        "evidence": "Static-confirmed; runtime use confirmed by persistence",
        "production_safe": "conditional",
        "reference": "addresses.py, pickup_persistence.py",
        "notes": "Corrects superseded 0x802FCE20; surrounding overlay/runtime space is not inferred from this word."
      }
    ]
  }
};
