// Patch-site overlay snapshot from the canonical MKMSZR registry.
window.MKMSZ_PATCH_DATA = {
  "snapshot": "2026-09-27",
  "sourceCommit": "f00c1d97cc5b491593790e8fe0544176c63ff26a",
  "patches": [
    {
      "id": "prod-0",
      "class": "production",
      "owner": "Stage selector",
      "romSite": "0x0000DD60",
      "romStart": 56672,
      "romEnd": 56676,
      "romExact": false,
      "context": "—",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "0x2414000A",
      "effect": "Last compact menu index becomes 7",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-1",
      "class": "production",
      "owner": "Stage selector",
      "romSite": "0x0000DD64",
      "romStart": 56676,
      "romEnd": 56680,
      "romExact": false,
      "context": "—",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "0x2A82000B",
      "effect": "Entry count becomes 8",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-2",
      "class": "production",
      "owner": "Stage selector",
      "romSite": "0x0000E028",
      "romStart": 57384,
      "romEnd": 57388,
      "romExact": false,
      "context": "—",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "JAL 0x8002830C",
      "effect": "JAL debug menu 0x8000D0B8",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-3",
      "class": "production",
      "owner": "Stage selector",
      "romSite": "0x00015CD0",
      "romStart": 89296,
      "romEnd": 89300,
      "romExact": false,
      "context": "—",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "load from 0x800C11E0",
      "effect": "JAL compact-index mapper",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-4",
      "class": "production",
      "owner": "Four-box input",
      "romSite": "0x0001674C",
      "romStart": 91980,
      "romEnd": 91984,
      "romExact": false,
      "context": "—",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "3C03802F 9463CE18",
      "effect": "Call switching action routine, then resume 0x80015B54",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-5",
      "class": "production",
      "owner": "Rainbow outfit",
      "romSite": "0x0001C9A0..0x0001C9AF",
      "romStart": 117152,
      "romEnd": 117168,
      "romExact": true,
      "context": "0x8001BDA0",
      "vaStart": 2147597728,
      "vaEnd": 2147597744,
      "physicalStart": 114080,
      "physicalEnd": 114096,
      "expected": "guarded first four frame-setup instructions",
      "effect": "rainbow mode only: tail-jump through uncached helper 0xA01AF700, which replays displaced instructions and resumes 0x8001BDB0",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-6",
      "class": "production",
      "owner": "Persistence",
      "romSite": "0x000396CC",
      "romStart": 235212,
      "romEnd": 235216,
      "romExact": false,
      "context": "0x80038ACC",
      "vaStart": 2147715788,
      "vaEnd": 2147715792,
      "physicalStart": 232140,
      "physicalEnd": 232144,
      "expected": "3C03800A 8C63A910",
      "effect": "Restore collected flags, resume 0x80038AD4",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-7",
      "class": "production",
      "owner": "Persistence",
      "romSite": "0x0003A018",
      "romStart": 237592,
      "romEnd": 237596,
      "romExact": false,
      "context": "0x80039418",
      "vaStart": 2147718168,
      "vaEnd": 2147718172,
      "physicalStart": 234520,
      "physicalEnd": 234524,
      "expected": "ACA2002C",
      "effect": "Capture stage/ordinal after collected store while preserving displaced store",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-8",
      "class": "production",
      "owner": "Box indicator",
      "romSite": "0x0005D9CC",
      "romStart": 383436,
      "romEnd": 383440,
      "romExact": false,
      "context": "HUD function",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "JAL 0x8001EAE4",
      "effect": "JAL native box-indicator wrapper",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-9",
      "class": "production",
      "owner": "Arena reservation",
      "romSite": "0x00066F60..0x00066F67",
      "romStart": 421728,
      "romEnd": 421736,
      "romExact": true,
      "context": "arena construction",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "3C02801B 2442F420",
      "effect": "3C02801B 24423420 (arena floor 0x801B3420)",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-10",
      "class": "production",
      "owner": "Bootstrap",
      "romSite": "0x00066FE0",
      "romStart": 421856,
      "romEnd": 421860,
      "romExact": false,
      "context": "0x800663E0",
      "vaStart": 2147902432,
      "vaEnd": 2147902436,
      "physicalStart": 418784,
      "physicalEnd": 418788,
      "expected": "guarded native sequence",
      "effect": "Call native bootstrap stub",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-11",
      "class": "production",
      "owner": "Arena reservation",
      "romSite": "0x00066FE4..0x00066FEB",
      "romStart": 421860,
      "romEnd": 421868,
      "romExact": true,
      "context": "second arena construction / bootstrap precondition",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "3C02801B 2442F420",
      "effect": "ArenaReservation changes the low immediate to 0x3420; bootstrap later supersedes 0x66FE4 while preserving the same floor",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-12",
      "class": "production",
      "owner": "Logo bypass",
      "romSite": "0x0007A3F4",
      "romStart": 500724,
      "romEnd": 500728,
      "romExact": false,
      "context": "0x800797F4",
      "vaStart": 2147981300,
      "vaEnd": 2147981304,
      "physicalStart": 497652,
      "physicalEnd": 497656,
      "expected": "0C01F113 00000000 0C01F143 00000000 0C018576 24040080",
      "effect": "first word 0x10000003 (beq zero,zero,+3); preserves fade/title",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-13",
      "class": "production",
      "owner": "Four-box mask",
      "romSite": "0x0007B900..0x0007B94B",
      "romStart": 506112,
      "romEnd": 506188,
      "romExact": true,
      "context": "0x8007AD00",
      "vaStart": 2147986688,
      "vaEnd": 2147986764,
      "physicalStart": 503040,
      "physicalEnd": 503116,
      "expected": "guarded stock sanitizer body",
      "effect": "Replace with stage-local key mask-copy routine",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-14",
      "class": "production",
      "owner": "Four-box load",
      "romSite": "0x0007B94C..0x0007B97F",
      "romStart": 506188,
      "romEnd": 506240,
      "romExact": true,
      "context": "0x8007AD4C",
      "vaStart": 2147986764,
      "vaEnd": 2147986816,
      "physicalStart": 503116,
      "physicalEnd": 503168,
      "expected": "guarded stock default-loader body",
      "effect": "Rebuild live inventory from authoritative backing box",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-15",
      "class": "production",
      "owner": "Stage selector",
      "romSite": "0x0009B7DC",
      "romStart": 636892,
      "romEnd": 636896,
      "romExact": false,
      "context": "0x8009ABDC",
      "vaStart": 2148117468,
      "vaEnd": 2148117472,
      "physicalStart": 633820,
      "physicalEnd": 633824,
      "expected": "12 stock pointers",
      "effect": "Eight safe stage labels plus zeros",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-16",
      "class": "production",
      "owner": "Native payload",
      "romSite": "0x000A5154",
      "romStart": 676180,
      "romEnd": 676184,
      "romExact": false,
      "context": "file entry 0x1B",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded stock file-table entry",
      "effect": "Point file 0x1B at the production payload source/destination descriptor",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-17",
      "class": "production",
      "owner": "Four-box keys",
      "romSite": "0x000A6BE4..0x000A6C0B",
      "romStart": 682980,
      "romEnd": 683020,
      "romExact": true,
      "context": "0x800A5FE4..0x800A600B",
      "vaStart": 2148163556,
      "vaEnd": 2148163596,
      "physicalStart": 679908,
      "physicalEnd": 679948,
      "expected": "guarded obsolete default-inventory template",
      "effect": "Write item-0x0D..0x22 stage map",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-18",
      "class": "production",
      "owner": "Four-box state",
      "romSite": "0x000A6C48..0x000A6CEF",
      "romStart": 683080,
      "romEnd": 683248,
      "romExact": true,
      "context": "0x800A6048..0x800A60EF",
      "vaStart": 2148163656,
      "vaEnd": 2148163824,
      "physicalStart": 680008,
      "physicalEnd": 680176,
      "expected": "guarded stock data",
      "effect": "Four backing boxes, active state, and MKBX magic",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-19",
      "class": "production",
      "owner": "Glass mask",
      "romSite": "0x000A6E88",
      "romStart": 683656,
      "romEnd": 683660,
      "romExact": false,
      "context": "item-use table",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "0x80071F58",
      "effect": "Inert 0x80071F50",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-20",
      "class": "production",
      "owner": "Branding",
      "romSite": "0x000AF998..0x000AFA23",
      "romStart": 719256,
      "romEnd": 719396,
      "romExact": true,
      "context": "boot strings",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded legal-text storage",
      "effect": "Product title, spaced RANDOMIZER, configurable <CHAR> EDITION, 2026 credit, seeded joke, author",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-21",
      "class": "production",
      "owner": "Box indicator",
      "romSite": "0x000AFA24..0x000AFA97",
      "romStart": 719396,
      "romEnd": 719512,
      "romExact": true,
      "context": "0x800AEE24..",
      "vaStart": 2148199972,
      "vaEnd": 2148200088,
      "physicalStart": 716324,
      "physicalEnd": 716440,
      "expected": "guarded legal-text region",
      "effect": "Native wrapper and BOX 1 OF 4 text",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-22",
      "class": "production",
      "owner": "Branding",
      "romSite": "0x000AFA98..0x000AFABB",
      "romStart": 719512,
      "romEnd": 719548,
      "romExact": true,
      "context": "boot strings",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded license text",
      "effect": "NOT LICENSED BY NINTENDO",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-23",
      "class": "production",
      "owner": "Outfit",
      "romSite": "0x0078E16C..",
      "romStart": 7922028,
      "romEnd": 7922032,
      "romExact": false,
      "context": "palette data",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded 64-color BGR555 source palette",
      "effect": "Transform clothing indices 0x21..0x3F",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-24",
      "class": "production",
      "owner": "XP progression",
      "romSite": "0x0002EDA8",
      "romStart": 191912,
      "romEnd": 191916,
      "romExact": false,
      "context": "0x8002E1A8",
      "vaStart": 2147672488,
      "vaEnd": 2147672492,
      "physicalStart": 188840,
      "physicalEnd": 188844,
      "expected": "AC24200C",
      "effect": "NOP central XP store",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-25",
      "class": "production",
      "owner": "XP progression",
      "romSite": "0x00054CE8",
      "romStart": 347368,
      "romEnd": 347372,
      "romExact": false,
      "context": "0x800540E8",
      "vaStart": 2147827944,
      "vaEnd": 2147827948,
      "physicalStart": 344296,
      "physicalEnd": 344300,
      "expected": "AC23200C",
      "effect": "NOP direct XP store",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-26",
      "class": "production",
      "owner": "XP progression",
      "romSite": "0x00057D60",
      "romStart": 359776,
      "romEnd": 359780,
      "romExact": false,
      "context": "0x80057160",
      "vaStart": 2147840352,
      "vaEnd": 2147840356,
      "physicalStart": 356704,
      "physicalEnd": 356708,
      "expected": "AC23200C",
      "effect": "NOP direct XP store",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-27",
      "class": "production",
      "owner": "XP progression",
      "romSite": "0x00057E2C",
      "romStart": 359980,
      "romEnd": 359984,
      "romExact": false,
      "context": "0x8005722C",
      "vaStart": 2147840556,
      "vaEnd": 2147840560,
      "physicalStart": 356908,
      "physicalEnd": 356912,
      "expected": "AC23200C",
      "effect": "NOP direct XP store",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-28",
      "class": "production",
      "owner": "XP progression UI",
      "romSite": "0x00063704",
      "romStart": 407300,
      "romEnd": 407304,
      "romExact": false,
      "context": "combo XP UI",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "JAL native text renderer",
      "effect": "Suppress combo EXPERIENCE label",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-29",
      "class": "production",
      "owner": "XP progression UI",
      "romSite": "0x00063724",
      "romStart": 407332,
      "romEnd": 407336,
      "romExact": false,
      "context": "combo XP UI",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "JAL native text renderer",
      "effect": "Suppress combo EXPERIENCE value",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-30",
      "class": "production",
      "owner": "XP progression",
      "romSite": "0x000A6FFC..",
      "romStart": 684028,
      "romEnd": 684032,
      "romExact": false,
      "context": "0x800A63FC",
      "vaStart": 2148164604,
      "vaEnd": 2148164608,
      "physicalStart": 680956,
      "physicalEnd": 680960,
      "expected": "guarded signed stage-cap halfwords",
      "effect": "Main-stage caps become 20000",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-31",
      "class": "production",
      "owner": "Title branding",
      "romSite": "0x000A5478",
      "romStart": 676984,
      "romEnd": 676988,
      "romExact": false,
      "context": "file entry 0x5E",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded stock file-table entry",
      "effect": "Repoint title package to generated high-ROM copy",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-32",
      "class": "production",
      "owner": "Rainbow outfit",
      "romSite": "0x000A5664",
      "romStart": 677476,
      "romEnd": 677480,
      "romExact": false,
      "context": "file entry 0x87",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "stock 0x00748920..0x0078E300, raw flag 0",
      "effect": "rainbow mode only: repoint intact Sub-Zero file plus 64-palette bank to 0x00F20000..0x00F679E0",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-33",
      "class": "production",
      "owner": "Title branding",
      "romSite": "0x000B3364 palette base",
      "romStart": 734052,
      "romEnd": 734056,
      "romExact": false,
      "context": "0x800B2764",
      "vaStart": 2148214628,
      "vaEnd": 2148214632,
      "physicalStart": 730980,
      "physicalEnd": 730984,
      "expected": "selected guarded Candidate-B-unused CI8 entries",
      "effect": "Replace 15 entries with grayscale antialias ramp",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-turn-action",
      "class": "production",
      "owner": "TURN action gate",
      "romSite": "0x00016354",
      "romStart": 90964,
      "romEnd": 90972,
      "romExact": true,
      "context": "0x80015754",
      "vaStart": 2147571540,
      "vaEnd": 2147571548,
      "physicalStart": 87892,
      "physicalEnd": 87900,
      "expected": "A62406DC 3C058003",
      "effect": "Jump to guarded v10/v06 action helper; suppress Turn states 23/24 only when effective LOCK is active",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-turn-decision",
      "class": "production",
      "owner": "TURN direction decision",
      "romSite": "0x00029FB0",
      "romStart": 171952,
      "romEnd": 171960,
      "romExact": true,
      "context": "0x800293B0",
      "vaStart": 2147652528,
      "vaEnd": 2147652536,
      "physicalStart": 168880,
      "physicalEnd": 168888,
      "expected": "8C640704 24020305",
      "effect": "JAL production TURN decision helper; TOGGLE stays stock, LOCK uses accepted v10 facing correction",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-turn-release",
      "class": "production",
      "owner": "TURN release path",
      "romSite": "0x0002A0DC",
      "romStart": 172252,
      "romEnd": 172260,
      "romExact": true,
      "context": "0x800294DC",
      "vaStart": 2147652828,
      "vaEnd": 2147652836,
      "physicalStart": 169180,
      "physicalEnd": 169188,
      "expected": "8C820638 94430000",
      "effect": "JAL leaf-only v06 release helper with bounded direct forced-facing scan",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-turn-menu",
      "class": "production",
      "owner": "GAME SETTINGS TURN menu wrapper",
      "romSite": "0x000770B8",
      "romStart": 487608,
      "romEnd": 487616,
      "romExact": true,
      "context": "frontend OPTIONS -> GAME SETTINGS call",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "0C01D9AF 02402021",
      "effect": "JAL frontend-resident wrapper; mirror durable TURN preference into stock editor and commit it on return",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-toasty-trigger",
      "class": "production",
      "owner": "Donor-backed reaction trigger",
      "romSite": "0x0002EB28",
      "romStart": 191272,
      "romEnd": 191276,
      "romExact": false,
      "context": "0x8002DF28",
      "vaStart": 2147671848,
      "vaEnd": 2147671852,
      "physicalStart": 188200,
      "physicalEnd": 188204,
      "expected": "0C00B81E 03C02821",
      "effect": "JAL shared production dispatcher at the successful/unblocked reaction seam",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-toasty-init",
      "class": "production",
      "owner": "Donor-backed feature stage init",
      "romSite": "0x0005CCE0",
      "romStart": 380128,
      "romEnd": 380136,
      "romExact": true,
      "context": "0x8005C0E0",
      "vaStart": 2147864800,
      "vaEnd": 2147864808,
      "physicalStart": 377056,
      "physicalEnd": 377064,
      "expected": "3C048029 8C841C10",
      "effect": "Load optional file 0x1A module and initialize the production feature",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-toasty-hud",
      "class": "production",
      "owner": "Donor-backed HUD compositor",
      "romSite": "0x0005D2E0",
      "romStart": 381664,
      "romEnd": 381672,
      "romExact": true,
      "context": "0x8005C6E0",
      "vaStart": 2147866336,
      "vaEnd": 2147866344,
      "physicalStart": 378592,
      "physicalEnd": 378600,
      "expected": "0C007AB9 A0C20046",
      "effect": "JAL shared production dispatcher while preserving stock HUD submission",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-shared-file1a",
      "class": "production",
      "owner": "Shared TURN / modern controls / optional Toasty transport",
      "romSite": "0x000A5148",
      "romStart": 676168,
      "romEnd": 676180,
      "romExact": true,
      "context": "file entry 0x1A",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded clean zero entry",
      "effect": "Points at mandatory TURN and modern controls; optional CI4 Toasty extends the same file",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-sektor-v85",
      "class": "proof-only",
      "owner": "Sektor v85 deferred projectile publication",
      "romSite": "ROM 0x316C8 / VA 0x80030AC8",
      "romStart": 202440,
      "romEnd": 202444,
      "romExact": false,
      "context": "0x80030AC8 plus proof helper [0x9AE10,0x9AE90)",
      "vaStart": 2147683016,
      "vaEnd": 2147683020,
      "physicalStart": 199368,
      "physicalEnd": 199372,
      "expected": "exact-v75 token JAL 0x80024650",
      "effect": "Built but statically rejected on ordinary straight flight: global insertion suppression has no reachable reinsertion on the normal mode-zero branch",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-34",
      "class": "proof-only",
      "owner": "First ordinary Fire enemy type 0x0A -> 0x09",
      "romSite": "ROM 0xB44AA / RAM 0x800B38AA",
      "romStart": 738474,
      "romEnd": 738478,
      "romExact": false,
      "context": "ROM 0xB44AA / RAM 0x800B38AA",
      "vaStart": 2148219050,
      "vaEnd": 2148219054,
      "physicalStart": 735402,
      "physicalEnd": 735406,
      "expected": "Proof-only / artifact-specific",
      "effect": "Runtime-confirmed, not production",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-35",
      "class": "proof-only",
      "owner": "Relocated/expanded Fire pickup resources",
      "romSite": "Fire resource entry ROM 0xA52E0",
      "romStart": 676576,
      "romEnd": 676580,
      "romExact": false,
      "context": "Fire resource entry ROM 0xA52E0",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "Proof-only / artifact-specific",
      "effect": "Runtime-confirmed architecture proof",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-36",
      "class": "proof-only",
      "owner": "Dedicated Prison-key award callback",
      "romSite": "VA 0x8008EAEC / ROM 0x8F6EC",
      "romStart": 587500,
      "romEnd": 587504,
      "romExact": false,
      "context": "VA 0x8008EAEC / ROM 0x8F6EC",
      "vaStart": 2148068076,
      "vaEnd": 2148068080,
      "physicalStart": 584428,
      "physicalEnd": 584432,
      "expected": "Proof-only / artifact-specific",
      "effect": "Runtime-confirmed proof; conflicts with production allocation rom.production.inventory_action_cave",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-37",
      "class": "proof-only",
      "owner": "Foreign fighter file load/allocation sequence",
      "romSite": "Fire overlay tail ROM 0xE2148..0xE216B",
      "romStart": 926024,
      "romEnd": 926060,
      "romExact": true,
      "context": "Fire overlay tail ROM 0xE2148..0xE216B",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "Proof-only / artifact-specific",
      "effect": "Runtime-confirmed monk import proof",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-38",
      "class": "proof-only",
      "owner": "Replace ordinary Fire Hulk types with Temple monk type 0x01",
      "romSite": "Seven Fire type-0x0A halfwords",
      "romStart": null,
      "romEnd": null,
      "romExact": false,
      "context": "Seven Fire type-0x0A halfwords",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "Proof-only / artifact-specific",
      "effect": "Runtime-confirmed bounded proof",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-settings-right",
      "class": "production",
      "owner": "GAME SETTINGS right-edit dispatcher",
      "romSite": "0x00077480..0x000775DB",
      "romStart": 488576,
      "romEnd": 488924,
      "romExact": true,
      "context": "Frontend right-edit body",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded stock edit body",
      "effect": "Integrated TURN/ATTACK/SPECIALS/JUMP/RUN right-edit dispatch",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-settings-left",
      "class": "production",
      "owner": "GAME SETTINGS left-edit dispatcher",
      "romSite": "0x00077600..0x0007769B",
      "romStart": 488960,
      "romEnd": 489116,
      "romExact": true,
      "context": "Frontend left-edit body",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded stock edit body",
      "effect": "Integrated TURN/ATTACK/SPECIALS/JUMP/RUN left-edit dispatch",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-settings-values",
      "class": "production",
      "owner": "GAME SETTINGS value draws",
      "romSite": "0x00077888..0x0007790F",
      "romStart": 489608,
      "romEnd": 489744,
      "romExact": true,
      "context": "Frontend value draws",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded stock Lives/Continues draw bodies",
      "effect": "ATTACK and SPECIALS CLASSIC/MODERN values at compact coordinates",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-settings-jump",
      "class": "production",
      "owner": "GAME SETTINGS JUMP draw/cursor hook",
      "romSite": "0x00077910..0x0007791B",
      "romStart": 489744,
      "romEnd": 489756,
      "romExact": true,
      "context": "Frontend loop tail",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "24080002 AFD006F4 AFC806F8",
      "effect": "JUMP helper and cursor type ownership",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "prod-settings-cursor",
      "class": "production",
      "owner": "GAME SETTINGS compact cursor coordinates",
      "romSite": "0x000AF824..0x000AF833",
      "romStart": 718884,
      "romEnd": 718900,
      "romExact": true,
      "context": "Frontend cursor table",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded stock type-2 four-entry table",
      "effect": "Compact TURN/ATTACK/SPECIALS/JUMP/RUN/EXIT positions in the integrated frontend",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-attack-event",
      "class": "proof-only",
      "owner": "ATTACK event-0 seam",
      "romSite": "0x00015738..0x0001573F",
      "romStart": 87864,
      "romEnd": 87872,
      "romExact": true,
      "context": "ATTACK bounded proof-only full-composition check",
      "vaStart": 2147568440,
      "vaEnd": 2147568448,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "0C005570 24070001",
      "effect": "Disposable capture/event trampoline, preserves delay slot",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-attack-block",
      "class": "proof-only",
      "owner": "ATTACK Block seam",
      "romSite": "0x0002A848..0x0002A84F",
      "romStart": 174152,
      "romEnd": 174160,
      "romExact": true,
      "context": "ATTACK bounded proof-only full-composition check",
      "vaStart": 2147654728,
      "vaEnd": 2147654736,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "30624000 1440FF23",
      "effect": "Proof Block stub; CLASSIC replays stock logic, MODERN schedules LP",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-attack-combo",
      "class": "proof-only",
      "owner": "ATTACK stock combo-parser seam",
      "romSite": "0x0004E3AC..0x0004E3B3",
      "romStart": 320428,
      "romEnd": 320436,
      "romExact": true,
      "context": "ATTACK bounded proof-only full-composition check",
      "vaStart": 2147801004,
      "vaEnd": 2147801012,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "000210C0 8CA306E0",
      "effect": "Proof combo stub; replays displaced actor load and CLASSIC shift",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-attack-name",
      "class": "proof-only",
      "owner": "ATTACK disposable frontend label",
      "romSite": "0x000AF71C",
      "romStart": 718620,
      "romEnd": 718624,
      "romExact": false,
      "context": "ATTACK bounded proof-only full-composition check",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded COMBOS row label",
      "effect": "Historical disposable ATTACK label; superseded by the integrated v02 frontend",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-attack-value",
      "class": "proof-only",
      "owner": "ATTACK disposable frontend value pointer",
      "romSite": "0x000AF708",
      "romStart": 718600,
      "romEnd": 718604,
      "romExact": false,
      "context": "ATTACK bounded proof-only full-composition check",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded ASSIST pointer 0x800AEAD8",
      "effect": "Historical disposable MODERN pointer; superseded by the integrated v02 frontend",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-attack-owned-combo",
      "class": "proof-only",
      "owner": "ATTACK guarded combo stub",
      "romSite": "0x000775D0..0x000775DB",
      "romStart": 488912,
      "romEnd": 488924,
      "romExact": true,
      "context": "Existing production frontend/bootstrap ownership",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded generated body or zero-filled tail",
      "effect": "Proof-only edit inside existing production allocation; original production bytes unchanged",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-attack-owned-block",
      "class": "proof-only",
      "owner": "ATTACK guarded block stub",
      "romSite": "0x00077688..0x00077693",
      "romStart": 489096,
      "romEnd": 489108,
      "romExact": true,
      "context": "Existing production frontend/bootstrap ownership",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded generated body or zero-filled tail",
      "effect": "Proof-only edit inside existing production allocation; original production bytes unchanged",
      "source": "Address-and-Patch-Site-Registry.md"
    },
    {
      "id": "proof-attack-owned-capture",
      "class": "proof-only",
      "owner": "ATTACK guarded capture stub",
      "romSite": "0x0009AE18..0x0009AE27",
      "romStart": 634392,
      "romEnd": 634408,
      "romExact": true,
      "context": "Existing production frontend/bootstrap ownership",
      "vaStart": null,
      "vaEnd": null,
      "physicalStart": null,
      "physicalEnd": null,
      "expected": "guarded generated body or zero-filled tail",
      "effect": "Proof-only edit inside existing production allocation; original production bytes unchanged",
      "source": "Address-and-Patch-Site-Registry.md"
    }
  ]
};
