// Curated public-facing snapshot from current canonical MKMSZR owners.
window.MKMSZ_PROJECT_DATA = {
  "snapshot": "2026-10-02",
  "sourceCommit": "b19837ee97e5d615f8d16048abb8a98da4909702",
  "featureBoard": [
    {
      "group": "Core",
      "name": "Safe ROM Patching",
      "state": "production",
      "kind": "have",
      "detail": "Supported-ROM validation, separate output, guarded writes, and N64 checksum update are production behavior.",
      "source": "Project-Status.md",
      "technicalName": "Guarded clean-ROM patching",
      "track": "Core",
      "scope": "1.0",
      "effort": 3,
      "completion": 1
    },
    {
      "group": "Core",
      "name": "Native Runtime",
      "state": "production",
      "kind": "have",
      "detail": "The production arena floor now reserves 16 KiB for MKMSZR. Runtime V2 owns the first 1 KiB and a bounded build-time expansion pool owns the remaining 15 KiB; the reservation is runtime-confirmed across all eight safe stages.",
      "source": "Project-Status.md",
      "technicalName": "Native Runtime V2",
      "track": "Core",
      "scope": "1.0",
      "effort": 6,
      "completion": 1,
      "introduced": "Runtime V2"
    },
    {
      "group": "Flow",
      "name": "Stage Select",
      "state": "production",
      "kind": "have",
      "detail": "Compact eight-stage selector is Runtime-confirmed across all safe stages. Accepted v03a adds the title-blue animated cursor and exactly one title MOVE sound per valid Up/Down press without the delayed corruption seen in rejected v02. Start selects the highlighted stage; a separate confirmation chime remains deliberately deferred.",
      "source": "Project-Status.md",
      "technicalName": "Safe Stage Select",
      "track": "Core",
      "scope": "1.0",
      "effort": 3,
      "completion": 1,
      "introduced": "v03a"
    },
    {
      "group": "Items",
      "name": "Persistent Pickups",
      "state": "beta",
      "kind": "have",
      "detail": "Representative collect/restore coverage exists in all eight main stages; all 84 ordinary records are cataloged.",
      "source": "Project-Status.md",
      "technicalName": "Ordinary pickup persistence",
      "track": "Core",
      "scope": "1.0",
      "effort": 6,
      "completion": 0.9
    },
    {
      "group": "Items",
      "name": "Seeded Item Shuffle",
      "state": "beta",
      "kind": "have",
      "detail": "All 84 ordinary records participate in the current deterministic interim stage-local mode. Wind has a Static-confirmed ownership limitation: complete-tuple shuffling can move stage/checkpoint callback state with the reward, so STAGE-LOCAL:V1 is an interim product mode and must not become the 1.0 global-materializer model.",
      "source": "Project-Status.md",
      "technicalName": "Stage-local seeded shuffle",
      "track": "Core",
      "scope": "1.0",
      "effort": 5,
      "completion": 0.75
    },
    {
      "group": "Inventory",
      "name": "Four Inventory Boxes",
      "state": "beta",
      "kind": "have",
      "detail": "Box switching, transition preservation, and stage-local foreign-key masking are Runtime-confirmed on documented routes. Lifecycle v06 preserves inventory through death/Continue and Runtime-confirms final Game Over clearing of run-scoped inventory/progression authority while preserving GAME SETTINGS. Immediate post-pickup foreign-key re-masking is Runtime-confirmed in a bounded v02 proof and still needs normal guarded production ownership.",
      "source": "Project-Status.md",
      "technicalName": "Four inventory boxes",
      "track": "Core",
      "scope": "1.0",
      "effort": 5,
      "completion": 0.9
    },
    {
      "group": "Progression",
      "name": "Powers as Pickups",
      "state": "beta",
      "kind": "have",
      "detail": "Build-time setting, default ON. ON keeps the established nine generated progression rewards and pickup-driven XP path; OFF leaves generated Herbs ordinary, retains stock combat XP, combo EXPERIENCE display, stage caps, and normal four-box resume behavior. The pickup mode is Runtime-confirmed on bounded early-tier/lifecycle routes; the new OFF composition is Implementation/static-confirmed and runtime Pending.",
      "source": "XP-and-Progression.md",
      "technicalName": "POWERS AS PICKUPS: ON / OFF",
      "track": "Core",
      "scope": "1.0",
      "effort": 5,
      "completion": 0.85
    },
    {
      "group": "Progression",
      "name": "Required Power Upgrades",
      "state": "beta",
      "kind": "have",
      "detail": "Build-time Fortress-gate setting. VANILLA preserves the exact stock 5100-XP requirement; CUSTOM accepts 0..9 native thresholds; SEED deterministically selects 0..9 from its own RNG namespace. The guarded patch is implemented/static-confirmed; final-fight runtime coverage and whole-run solver/HUD integration remain pending.",
      "source": "XP-and-Progression.md",
      "technicalName": "REQUIRED POWER UPGRADES: VANILLA / CUSTOM / SEED",
      "track": "Core",
      "scope": "1.0",
      "effort": 4,
      "completion": 0.75
    },
    {
      "group": "Progression",
      "name": "Shuffled Power Order",
      "state": "proof",
      "kind": "want",
      "detail": "Default OFF preserves vanilla Power Up order. ON has a Runtime-confirmed bounded nine-slot mechanism that keeps gameplay gates and native Power Ups icon/help presentation synchronized, with only the Ice Shatter freezing prerequisite; Slide and Super Slide may appear in either order. Shared product implementation and web UI exist, but current Project Status still lists repository CI/merge/deployment as the remaining production gate.",
      "source": "XP-and-Progression.md",
      "technicalName": "SHUFFLE POWER PROGRESSION: OFF / ON",
      "track": "Core",
      "scope": "extra",
      "effort": 3,
      "completion": 0.65,
      "introduced": "power-order v04 proof"
    },
    {
      "group": "UI",
      "name": "In-Game Settings",
      "state": "beta",
      "kind": "have",
      "detail": "The shared browser/CLI builder now includes the Runtime-confirmed v02 GAME SETTINGS composition: TURN, ATTACK, SPECIALS, JUMP, RUN, EXIT. ATTACK and SPECIALS offer CLASSIC / MODERN; JUMP offers DPAD / BUTTON when both are MODERN; RUN offers HOLD / AUTO. Gameplay claims remain bounded to the user-tested route.",
      "source": "Project-Status.md",
      "technicalName": "Native GAME SETTINGS menu",
      "track": "QoL",
      "scope": "extra",
      "effort": 2,
      "completion": 0.85,
      "introduced": "controls/CI4 v02 composition"
    },
    {
      "group": "Controls",
      "name": "Turn Lock",
      "state": "beta",
      "kind": "have",
      "detail": "Every generated ROM now includes TURN controls. TOGGLE is the vanilla default; LOCK uses the accepted v10 world-direction/facing-lock model, preserves held-Turn backpedal, and temporarily defers to stock forced-facing policy without changing the saved preference. Earth boss type 0x19 remains outside the runtime claim.",
      "source": "Project-Status.md",
      "technicalName": "TURN: TOGGLE / LOCK",
      "track": "QoL",
      "scope": "extra",
      "effort": 2,
      "completion": 0.8,
      "introduced": "TURN v10"
    },
    {
      "group": "UI",
      "name": "Inventory Box Indicator",
      "state": "production",
      "kind": "have",
      "detail": "BOX n OF 4 renders through the native text path.",
      "source": "Project-Status.md",
      "technicalName": "Native box indicator",
      "track": "QoL",
      "scope": "extra",
      "effort": 1,
      "completion": 1
    },
    {
      "group": "Presentation",
      "name": "Boot Branding",
      "state": "production",
      "kind": "have",
      "detail": "Custom legal-screen presentation and deterministic phrase namespace are runtime-confirmed.",
      "source": "Project-Status.md",
      "technicalName": "Boot branding + seeded phrase",
      "track": "4Fun",
      "scope": "extra",
      "effort": 1,
      "completion": 1
    },
    {
      "group": "Presentation",
      "name": "Randomizer Title Screen",
      "state": "beta",
      "kind": "have",
      "detail": "The accepted vector/typeset title and configurable <NAME> EDITION were visually confirmed through the production webapp. The native CI8 package uses a 16-color visual palette; every non-vanilla outfit option now also tints the title palette, while rainbow uses a fixed five-hue title treatment. Exact in-game acceptance of the color-linked variants remains Pending.",
      "source": "Presentation-and-Branding.md",
      "technicalName": "Randomizer title branding",
      "track": "4Fun",
      "scope": "extra",
      "effort": 2,
      "completion": 0.8,
      "introduced": "2026-09-29 accepted design"
    },
    {
      "group": "Presentation",
      "name": "Outfit Colors",
      "state": "production",
      "kind": "have",
      "detail": "Static modes and the 64-phase rainbow mode are normal browser/CLI options. Compact-tail v01 is runtime-confirmed across all eight safe stages: stock file 0x87 stays in place, only an 8 KiB palette bank is stored in high ROM, and the prior 0x459E0-byte duplicate fighter copy is gone.",
      "source": "Project-Status.md",
      "technicalName": "Outfit recoloring",
      "track": "4Fun",
      "scope": "extra",
      "effort": 2,
      "completion": 1,
      "introduced": "compact-tail v01"
    },
    {
      "group": "Product",
      "name": "Shared Web / CLI Builder",
      "state": "beta",
      "kind": "have",
      "detail": "Browser and CLI share one guarded patch core. Build-time Run Settings expose difficulty (default Very Hard), starting lives 1..10 (default 5), starting continues 0..5 (default 3), and Persistent HP (default ON), alongside progression choices and the Runtime-confirmed GAME SETTINGS control suite. The merged enemy-randomization switch defaults OFF. MKT Rev. 2 remains an optional donor for supported donor-backed features.",
      "source": "Web-Patcher-and-Product.md",
      "technicalName": "Browser / CLI shared patch core",
      "track": "Core",
      "scope": "1.0",
      "effort": 5,
      "completion": 0.9
    },
    {
      "group": "1.0",
      "name": "Cross-Stage Item Placement",
      "state": "needed",
      "kind": "need",
      "detail": "The shared-pipeline integration candidate is Runtime-confirmed + CI-green on the bounded v03 co-resident composition, including post-Temple relocation, immediate foreign-key masking, destination-native resource plans, and generalized Fortress boss-gate emission. PR #126 still requires explicit production promotion; normal seeded generation remains stage-local until the global generator/solver is implemented.",
      "source": "1.0-Requirements-and-Roadmap.md",
      "technicalName": "Global cross-stage item materialization",
      "track": "Core",
      "scope": "1.0",
      "effort": 10,
      "completion": 0.85,
      "introduced": "materializer v03 integration proof"
    },
    {
      "group": "1.0",
      "name": "Global Item Shuffle",
      "state": "needed",
      "kind": "need",
      "detail": "Replace eight independent stage-local pools with one global logical run.",
      "source": "1.0-Requirements-and-Roadmap.md",
      "technicalName": "Deterministic global shuffle",
      "track": "Core",
      "scope": "1.0",
      "effort": 8,
      "completion": 0.2
    },
    {
      "group": "1.0",
      "name": "Deterministic Retry Logic",
      "state": "needed",
      "kind": "need",
      "detail": "Rejected layouts must advance through an explicit deterministic attempt namespace.",
      "source": "1.0-Requirements-and-Roadmap.md",
      "technicalName": "Deterministic retry attempts",
      "track": "Core",
      "scope": "1.0",
      "effort": 4,
      "completion": 0.2
    },
    {
      "group": "1.0",
      "name": "Seed Solvability",
      "state": "needed",
      "kind": "need",
      "detail": "Every emitted 1.0 layout must reach the finalized completion predicate under current access rules.",
      "source": "1.0-Requirements-and-Roadmap.md",
      "technicalName": "Whole-run solvability solver",
      "track": "Core",
      "scope": "1.0",
      "effort": 10,
      "completion": 0.15
    },
    {
      "group": "1.0",
      "name": "Power Requirement Logic",
      "state": "needed",
      "kind": "need",
      "detail": "Vanilla / Custom / Seed gate modes are implemented, but the chosen requirement still must be retry-independent, modeled against pickup or earned-XP progression as appropriate, solver-enforced, and HUD-visible in the final global run.",
      "source": "1.0-Requirements-and-Roadmap.md",
      "technicalName": "Mode-aware required-power solver / HUD integration",
      "track": "Core",
      "scope": "1.0",
      "effort": 5,
      "completion": 0.5
    },
    {
      "group": "1.0",
      "name": "Randomizer HUD",
      "state": "needed",
      "kind": "need",
      "detail": "Checks, progression requirement/current state, box state, key progress, and pickup feedback are required.",
      "source": "1.0-Requirements-and-Roadmap.md",
      "technicalName": "Full native randomizer HUD",
      "track": "Core",
      "scope": "1.0",
      "effort": 8,
      "completion": 0.25
    },
    {
      "group": "Lifecycle",
      "name": "Run Health & Resources",
      "state": "beta",
      "kind": "have",
      "detail": "Lifecycle v06 is the Runtime-confirmed reference baseline: Very Hard, 9 total lives, 5 continues, Persistent HP ON. Damaged HP persists only across living departure/re-entry; ordinary death/Continue construct full-health replacements and retain stock decrements. The shared product path parameterizes the same guarded lifecycle for lives 1..10, continues 0..5, and Persistent HP ON/OFF; non-reference combinations are Implementation/CI-confirmed pending representative runtime sampling.",
      "source": "Persistence-Inventory-and-Lifecycle.md",
      "technicalName": "HP / LIVES / CONTINUES + Persistent HP",
      "track": "Core",
      "scope": "1.0",
      "effort": 7,
      "completion": 0.95,
      "introduced": "lifecycle v06"
    },
    {
      "group": "Lifecycle",
      "name": "New Run Reset",
      "state": "beta",
      "kind": "have",
      "detail": "Runtime-confirmed in lifecycle v06 on the accepted route. True final no-continues Game Over clears MKMSZR run state, inventory/progression authority, and Temple special-check persistence while preserving all five GAME SETTINGS preferences. The next run restores configured difficulty/lives/continues, full HP, and starter inventory.",
      "source": "Persistence-Inventory-and-Lifecycle.md",
      "technicalName": "Game Over / new-run reset",
      "track": "Core",
      "scope": "1.0",
      "effort": 4,
      "completion": 0.95,
      "introduced": "lifecycle v06"
    },
    {
      "group": "Lifecycle",
      "name": "Difficulty Setting",
      "state": "beta",
      "kind": "have",
      "detail": "Difficulty is now a build-time run setting, defaulting to Very Hard. Lifecycle v06 Runtime-confirms the Very Hard invariant across the accepted lifecycle and final reset. Other selectable values use the same guarded path and are Implementation/CI-confirmed pending representative runtime coverage.",
      "source": "1.0-Requirements-and-Roadmap.md",
      "technicalName": "DIFFICULTY: VERY EASY → VERY HARD",
      "track": "Core",
      "scope": "1.0",
      "effort": 3,
      "completion": 0.9,
      "introduced": "lifecycle v06"
    },
    {
      "group": "Items",
      "name": "Temple Special Check",
      "state": "beta",
      "kind": "have",
      "detail": "The 1.0 policy is resolved: logical Map item 0x0D is excluded from the randomizer pool, while the scripted Temple location remains a special check. Runtime-confirmed v02 preserves its elevator/rope progression, supports a non-Map reward/visual, persists collection through title → Temple re-entry outside the 84 ordinary bits, and is cleared by lifecycle v06 at final Game Over. Arbitrary global reward assignment belongs to the pending global materializer.",
      "source": "1.0-Requirements-and-Roadmap.md",
      "technicalName": "Temple scripted special check",
      "track": "Core",
      "scope": "1.0",
      "effort": 4,
      "completion": 0.9,
      "introduced": "Temple v02"
    },
    {
      "group": "1.0",
      "name": "Full Progression Validation",
      "state": "needed",
      "kind": "need",
      "detail": "All nine reward thresholds must work in the final production composition.",
      "source": "1.0-Requirements-and-Roadmap.md",
      "technicalName": "Full nine-tier progression validation",
      "track": "Core",
      "scope": "1.0",
      "effort": 4,
      "completion": 0.35
    },
    {
      "group": "1.0",
      "name": "Full 1.0 Seed Validation",
      "state": "needed",
      "kind": "need",
      "detail": "Final release gate after global items, solver, HUD, lifecycle, Map policy, Very Hard, and progression are composed.",
      "source": "1.0-Requirements-and-Roadmap.md",
      "technicalName": "Representative full global seed",
      "track": "Core",
      "scope": "1.0",
      "effort": 5,
      "completion": 0.05
    },
    {
      "group": "Research",
      "name": "Cross-Stage Item Research",
      "state": "proof",
      "kind": "want",
      "detail": "Bounded proofs cover external-to-embedded conversion, Prison multi-import visuals, Earth key donor closure, immediate Fire → Wind foreign-key masking, destination-owned checkpoint semantics, Fortress stress, and arbitrary boss-reward substitution. The shared file-0x1A integration candidate in PR #126 is Runtime-confirmed + CI-green after relocation to 0x801B0970..0x801B0A5F; explicit production promotion and the global generator/solver remain pending.",
      "source": "Project-Status.md",
      "technicalName": "Cross-stage item materialization / masking",
      "track": "Core",
      "scope": "extra",
      "effort": 4,
      "completion": 0.75,
      "introduced": "bounded materializer proof line"
    },
    {
      "group": "Enemies",
      "name": "Enemy Randomization",
      "state": "beta",
      "kind": "have",
      "detail": "The deterministic 104-record enemy planner is merged as a browser/CLI option and defaults OFF. It preserves five gated/special encounters and models Prison paging/set-piece auxiliaries; representative merged seed ENEMYPLAN05 is Runtime-confirmed. Compact Water PRIS15/16 and mixed PRIS14+16 fallback materialization is implemented on a follow-up branch with CI/product runtime promotion still pending; unresolved foreign semantics fail closed.",
      "source": "Project-Status.md",
      "technicalName": "ENEMY RANDOMIZATION: OFF / ON",
      "track": "4Fun",
      "scope": "extra",
      "effort": 5,
      "completion": 0.55,
      "introduced": "ENEMYPLAN05 representative proof"
    },
    {
      "group": "Research",
      "name": "Playable Sektor Research",
      "state": "proof",
      "kind": "future",
      "detail": "Proof-only line through v89: v75 is the stable missile-flight baseline, v87 confirms donor-faithful rocket assets/colors, and v89 Runtime-confirms synchronous texture-slot preparation before actor-list insertion removes the stale first frame. The six-pose Run v05 physical repack is Runtime-confirmed; the P28/P29 v06 rope-owner probe is bounded Runtime-confirmed. Storage/lifecycle/cleanup and general integration remain pending.",
      "source": "Project-Status.md",
      "technicalName": "MKT / Sektor takeover",
      "track": "4Fun",
      "scope": "extra",
      "effort": 6,
      "completion": 0.55,
      "introduced": "Sektor v89"
    },
    {
      "group": "Presentation",
      "name": "Toasty Voice",
      "state": "production",
      "kind": "have",
      "detail": "The genuine donor voice uses a dedicated MKMSZ audio route while stock pickup audio remains unchanged. The accepted v02 controls/CI4 Toasty composition is runtime-confirmed on the tested route.",
      "source": "Project-Status.md",
      "technicalName": "Donor-backed Toasty audio",
      "track": "4Fun",
      "scope": "extra",
      "effort": 1,
      "completion": 1,
      "introduced": "v46 / v47 composition"
    },
    {
      "group": "Presentation",
      "name": "Toasty Pop-In",
      "state": "production",
      "kind": "have",
      "detail": "The 78x85 lower-right presentation still uses nine CI4 (16-color) slices and a 16-entry palette, but production now stores the exact padded source through compact RLE plus a tiny native decoder. The Runtime-confirmed module is 0x1132 (4,402 bytes) at 0x801B1000..0x801B2131, reclaiming 3,262 bytes inside the existing 16 KiB reservation; production probability remains 8%.",
      "source": "Project-Status.md",
      "technicalName": "Donor-backed Toasty visual",
      "track": "4Fun",
      "scope": "extra",
      "effort": 2,
      "completion": 1,
      "introduced": "v47 + compact-source v01"
    },
    {
      "group": "Presentation",
      "name": "Seeded Scorpion Intro Clips",
      "state": "proof",
      "kind": "want",
      "detail": "Runtime-confirmed production candidate in PR #120. With valid MKT Rev. 2 donor, a dedicated deterministic seed domain replaces exactly one Temple intro position with one approved donor clip while leaving the other stock; no donor means no patch. The v06 production carrier/sample reservation is Runtime-confirmed, but the candidate still requires normal production promotion and the 11-clip pool is not runtime-exhausted.",
      "source": "Sounds-and-Music.md",
      "technicalName": "Seeded Temple intro audio",
      "track": "4Fun",
      "scope": "extra",
      "effort": 2,
      "completion": 0.75,
      "introduced": "Temple-audio v06 candidate"
    },
    {
      "group": "Research",
      "name": "MKT Move Import Research",
      "state": "partial",
      "kind": "future",
      "detail": "The adapter now has concrete projectile creation/placement, cadence-resampling, animation-context and first-visibility evidence from the Sektor missile line. Generic strike/reaction, effects/audio/palette lifetime and production composition remain incomplete.",
      "source": "Project-Status.md",
      "technicalName": "Generic donor-move adapter",
      "track": "4Fun",
      "scope": "extra",
      "effort": 5,
      "completion": 0.35
    },
    {
      "group": "Controls",
      "name": "Modern Attacks",
      "state": "beta",
      "kind": "have",
      "detail": "CLASSIC preserves stock attacks. MODERN translates Attack into context-appropriate stock punches, kicks, and combo events; Block + Attack cancels Block startup into the native LP path. Integrated in the shared builder and runtime-confirmed on the accepted v02 route.",
      "source": "Player-Actions-and-Special-Moves.md",
      "technicalName": "ATTACK: CLASSIC / MODERN",
      "track": "QoL",
      "scope": "extra",
      "effort": 2,
      "completion": 0.9,
      "introduced": "controls/CI4 v02 composition"
    },
    {
      "group": "Controls",
      "name": "Modern Specials",
      "state": "beta",
      "kind": "have",
      "detail": "CLASSIC leaves vanilla special recognition intact. MODERN maps facing-relative Special-button chords to native moves while retaining their stock eligibility, costs, and progression checks; Slide and Super Slide use their native recognizers with real XP. Integrated and runtime-confirmed on the accepted v02 route without proof-only XP forcing.",
      "source": "Player-Actions-and-Special-Moves.md",
      "technicalName": "SPECIALS: CLASSIC / MODERN",
      "track": "QoL",
      "scope": "extra",
      "effort": 2,
      "completion": 0.9,
      "introduced": "controls/CI4 v02 composition"
    },
    {
      "group": "Controls",
      "name": "Ice Blast Pickup Cancel",
      "state": "proof",
      "kind": "future",
      "detail": "Runtime-confirmed bounded 4Fun proof: while Sub-Zero is standing on a valid ordinary pickup, Pickup can interrupt normal ground Ice Blast and immediately enter the stock pickup transition. Stock input/proximity/facing and award behavior remain authoritative; the proof only broadens pickup eligibility for normal Ice and clears the native special lock after those gates pass. Directional/Air Ice and generalized action cancelling are outside the proof.",
      "source": "Pickup-Placement-and-Action-Cancel-Proofs.md",
      "technicalName": "Normal ground Ice Blast -> Pickup action cancel",
      "track": "4Fun",
      "scope": "extra",
      "effort": 1,
      "completion": 1,
      "introduced": "Ice Blast pickup-cancel v01 · 2026-10-02"
    },
    {
      "group": "Controls",
      "name": "Jump Button",
      "state": "beta",
      "kind": "have",
      "detail": "DPAD keeps stock locomotion jumps. BUTTON uses either LK or HK to jump while standing, moving, running, or hanging from a ledge; it becomes editable only when both ATTACK and SPECIALS are MODERN. Integrated and runtime-confirmed on the accepted v02 route.",
      "source": "Native-HUD-and-UI.md",
      "technicalName": "JUMP: DPAD / BUTTON",
      "track": "QoL",
      "scope": "extra",
      "effort": 1,
      "completion": 0.9,
      "introduced": "controls/CI4 v02 composition"
    },
    {
      "group": "Controls",
      "name": "Auto Run",
      "state": "beta",
      "kind": "have",
      "detail": "RUN: HOLD retains stock behavior; AUTO handles live Run-to-Walk-to-Run transitions while preserving analog auto-run and Run-based chords. Integrated in the shared builder and runtime-confirmed on the accepted v02 route.",
      "source": "Project-Status.md",
      "technicalName": "RUN: HOLD / AUTO",
      "track": "QoL",
      "scope": "extra",
      "effort": 1,
      "completion": 0.9,
      "introduced": "controls/CI4 v02 composition"
    }
  ],
  "compatibility": [
    {
      "area": "Architecture",
      "capability": "Source-level adapter strategy",
      "donor": "MKT semantics and assets",
      "target": "MKMSZ-native helpers/assets",
      "status": "established",
      "detail": "Accepted architecture: translate meaning and representation; do not relocate donor code.",
      "source": "MKT-to-MKMSZ-Compatibility-Layer.md"
    },
    {
      "area": "Lifecycle",
      "capability": "Process sleep / bounded yield",
      "donor": "process_sleep",
      "target": "Native process sleep",
      "status": "covered",
      "detail": "Target primitive established.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Lifecycle",
      "capability": "Action lock",
      "donor": "Donor action ownership",
      "target": "Native special-action lock",
      "status": "covered",
      "detail": "Target primitive established.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Lifecycle",
      "capability": "Action/context transfer",
      "donor": "body-propell action + context_jump",
      "target": "Installer + scheduler selector bridge",
      "status": "partial",
      "detail": "Host lifecycle is proven in bounded paths, but no generic donor action runner exists.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Movement",
      "capability": "Move toward opponent",
      "donor": "towards_x_vel",
      "target": "Native player horizontal velocity",
      "status": "partial",
      "detail": "Primitive exists; donor-to-target unit calibration is still needed generically.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Movement",
      "capability": "Stop movement",
      "donor": "stop_me",
      "target": "Native stop / clear motion",
      "status": "covered",
      "detail": "Target primitive established.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Movement",
      "capability": "Face opponent",
      "donor": "face_opponent",
      "target": "Find + face opponent helpers",
      "status": "covered",
      "detail": "Target primitive established.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Animation",
      "capability": "Select animation",
      "donor": "get_char_ani",
      "target": "Native animation selection",
      "status": "covered",
      "detail": "Target primitive established.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Animation",
      "capability": "Advance animation",
      "donor": "do_next_a9_frame / playback",
      "target": "Native animation advance",
      "status": "covered",
      "detail": "Target primitive established.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Animation",
      "capability": "Generic control-token translation",
      "donor": "Donor script callbacks/tokens",
      "target": "Equivalent MKMSZ callback/token",
      "status": "missing",
      "detail": "No generic translator yet.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Assets",
      "capability": "Frame / texture translation",
      "donor": "Heap-relative descriptors + codecs 22/24/15",
      "target": "Rebuilt descriptors + native Type-5",
      "status": "runtime",
      "detail": "Known donor formats can be decoded offline and rebuilt into runtime-proven MKMSZ-native storage.",
      "source": "MKT-Fighter-Asset-Translation.md"
    },
    {
      "area": "Assets",
      "capability": "Palette translation / binding",
      "donor": "MKT palette semantics",
      "target": "MKMSZ source palette + runtime binding",
      "status": "runtime",
      "detail": "Color conversion and Sektor palette binding are runtime-proven in bounded takeover work.",
      "source": "MKT-Fighter-Asset-Translation.md"
    },
    {
      "area": "Assets",
      "capability": "Direct donor codec consumption",
      "donor": "Raw MKT codec streams",
      "target": "MKMSZ renderer",
      "status": "rejected",
      "detail": "Rejected direct path: donor streams must be decoded and converted offline.",
      "source": "MKT-Fighter-Asset-Translation.md"
    },
    {
      "area": "Combat",
      "capability": "Strike check",
      "donor": "Strike index + record",
      "target": "Native strike dispatch + translated meaning",
      "status": "partial",
      "detail": "Host route exists; generic semantic mapping remains incomplete.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Combat",
      "capability": "Victim reactions",
      "donor": "Donor selector/function",
      "target": "Semantically equivalent MKMSZ reaction",
      "status": "missing",
      "detail": "No generic reaction map; player-victim grab/throw remains a known gap.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Combat",
      "capability": "Three-tick no-repel",
      "donor": "sans_repell_3",
      "target": "Narrow target separation bypass",
      "status": "missing",
      "detail": "Donor meaning is known; generic MKMSZ shim is not implemented.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Combos",
      "capability": "Normal combo graph",
      "donor": "MKT combo records",
      "target": "MKMSZ normal-combo graph",
      "status": "runtime",
      "detail": "Runtime-confirmed at Sektor v62 scope after translating game-local reaction selectors.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Combos",
      "capability": "Reaction-selector translation",
      "donor": "Game-local selector byte",
      "target": "MKMSZ selector chosen by meaning",
      "status": "partial",
      "detail": "Specific Sektor v62 translations work; no universal map yet.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Fighter",
      "capability": "Common Sektor animation takeover",
      "donor": "Sektor / robot animation families",
      "target": "Sub-Zero file 0x87 animation slots",
      "status": "runtime",
      "detail": "Broad common-action coverage, v62 combos, and the six-pose Run v05 physical repack are Runtime-confirmed in bounded proof routes.",
      "source": "Sub-Zero-to-Sektor-Animation-Mapping.md"
    },
    {
      "area": "Projectiles",
      "capability": "Projectile actor creation / ownership",
      "donor": "setup_proj_obj + create_proj_proc",
      "target": "Resource actor + secondary projectile actor/process path",
      "status": "partial",
      "detail": "Target actor/process ownership is statically reconciled and repeatedly exercised by the straight-missile proofs; a generic wrapper is still pending.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Projectiles",
      "capability": "Facing-aware launch placement",
      "donor": "retail (+5,+38)",
      "target": "Native local placement",
      "status": "runtime",
      "detail": "v72 runtime-confirms the retail N64 launch offset near the owner and correct facing mirroring.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Projectiles",
      "capability": "60 Hz donor → 30 Hz host flight cadence",
      "donor": "rocket1_flight_call velocity state",
      "target": "Two donor substeps folded into one target interval",
      "status": "runtime",
      "detail": "v74 runtime-confirms the folded cadence is stable; v75 provides a bounded 2x magnitude calibration that feels correct on the tested route, not a universal scale.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Projectiles",
      "capability": "First-visible projectile publication",
      "donor": "rocket frame becomes visible after setup",
      "target": "Frame bind + active-list insertion ordering",
      "status": "runtime",
      "detail": "v89 Runtime-confirms native synchronous texture-slot preparation before stock actor-list insertion. The first rocket frame uses the correct v87 dynamic asset/palette and retains v75 flight; storage and lifecycle remain proof-only.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Projectiles",
      "capability": "Projectile palette / effects / impact lifecycle",
      "donor": "rocket palette, smoke, sound, explosion, strike semantics",
      "target": "Native palette/audio/effect/strike translations",
      "status": "missing",
      "detail": "Palette translation is now materially stronger through v86/v87, but balanced palette release, smoke/sound/explosion, strike semantics, and production-safe generic integration remain distinct pending tasks.",
      "source": "MKT-Adapter-Primitives.md"
    },
    {
      "area": "Fighter",
      "capability": "Rare / special presentation",
      "donor": "Victory, projectile, dizzy, later reactions",
      "target": "Mythologies-specific slot families",
      "status": "partial",
      "detail": "P28/P29 v06 rope-owner probe is Runtime-confirmed on a bounded route; final fallback policy and many other rare families remain open.",
      "source": "Sub-Zero-to-Sektor-Animation-Mapping.md"
    },
    {
      "area": "Integration",
      "capability": "Arbitrary special-move integration",
      "donor": "MKT command/action behavior",
      "target": "MKMSZ input + action ABI",
      "status": "missing",
      "detail": "Not solved by animation replacement; requires the semantic adapter.",
      "source": "MKT-to-MKMSZ-Compatibility-Layer.md"
    },
    {
      "area": "Integration",
      "capability": "Production-safe fighter/move allocation",
      "donor": "Translated fighter/move payload",
      "target": "Current MKMSZR composition",
      "status": "pending",
      "detail": "Proof allocations establish feasibility only; conflict-free production composition remains pending.",
      "source": "MKT-Fighter-Asset-Translation.md"
    },
    {
      "area": "Architecture",
      "capability": "Direct binary/code compatibility",
      "donor": "MKT executable / PROCESS / OBJECT ABI",
      "target": "MKMSZ executable",
      "status": "rejected",
      "detail": "Not implied and explicitly not the accepted strategy.",
      "source": "MKT-to-MKMSZ-Compatibility-Layer.md"
    }
  ],
  "progressModel": {
    "note": "Atlas planning estimate only. 1.0 reaches 100% when effort-weighted release-scope work is complete; optional and experimental tracked work is shown beyond the 100% marker and does not increase 1.0 completion.",
    "releaseLabel": "1.0",
    "extraLabel": "Tracked extras"
  }
};
